const headers={'Cache-Control':'no-store','Content-Type':'application/json; charset=utf-8','X-Content-Type-Options':'nosniff'};
const json=(body,status=200,extra={})=>new Response(JSON.stringify(body),{status,headers:{...headers,...extra}});
const validId=id=>/^LG-\d{8}-[A-Z0-9]{5,12}$/.test(id);
const clean=(v,max)=>String(v??'').trim().slice(0,max);
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const refundId=id=>`RF-${id}-${crypto.randomUUID().replace(/-/g,'').slice(0,8).toUpperCase()}`;
async function logEvent(env,e){try{await env.GUARDIAN_DB.prepare(`INSERT OR IGNORE INTO guardian_payment_events (event_id,provider,event_type,guardian_id,payment_reference,amount_usd,currency,status,received_at,processed_at,error_code) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).bind(e.eventId,e.provider,e.event,e.guardianId||null,e.paymentReference||null,e.amount,e.currency||null,e.status,e.receivedAt,e.processedAt||null,e.errorCode||null).run()}catch{}}
async function processedPaymentReference(env,provider,paymentReference){if(!paymentReference)return null;try{return await env.GUARDIAN_DB.prepare(`SELECT event_id,guardian_id,status FROM guardian_payment_events WHERE provider=? AND payment_reference=? AND event_type='payment.succeeded' AND status='processed' ORDER BY received_at ASC LIMIT 1`).bind(provider,paymentReference).first()}catch{return null}}
async function updateCheckout(env,body,status,now,failureCode=null){const checkoutId=clean(body?.checkoutId,80),providerSessionId=clean(body?.providerSessionId||body?.sessionId,160);if(!checkoutId&&!providerSessionId)return;try{if(checkoutId)await env.GUARDIAN_DB.prepare(`UPDATE guardian_checkout_sessions SET status=?,failure_code=COALESCE(?,failure_code),updated_at=?,cancelled_at=CASE WHEN ?='cancelled' THEN COALESCE(cancelled_at,?) ELSE cancelled_at END,completed_at=CASE WHEN ?='completed' THEN COALESCE(completed_at,?) ELSE completed_at END WHERE checkout_id=?`).bind(status,failureCode,now,status,now,status,now,checkoutId).run();else await env.GUARDIAN_DB.prepare(`UPDATE guardian_checkout_sessions SET status=?,failure_code=COALESCE(?,failure_code),updated_at=?,cancelled_at=CASE WHEN ?='cancelled' THEN COALESCE(cancelled_at,?) ELSE cancelled_at END,completed_at=CASE WHEN ?='completed' THEN COALESCE(completed_at,?) ELSE completed_at END WHERE provider_session_id=?`).bind(status,failureCode,now,status,now,status,now,providerSessionId).run()}catch{}}
async function ensureSlots(env,editionKey,tier,limit){const sql=`WITH RECURSIVE seq(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM seq WHERE n<?) INSERT OR IGNORE INTO guardian_edition_slots (edition_key,slot_no,tier) SELECT ?,n,? FROM seq`;await env.GUARDIAN_DB.prepare(sql).bind(limit,editionKey,tier).run()}
async function claimSlot(env,editionKey,tier,limit,id,now){await ensureSlots(env,editionKey,tier,limit);return env.GUARDIAN_DB.prepare(`UPDATE guardian_edition_slots SET order_id=?,reserved_at=? WHERE edition_key=? AND slot_no=(SELECT slot_no FROM guardian_edition_slots WHERE edition_key=? AND order_id IS NULL ORDER BY slot_no LIMIT 1) AND order_id IS NULL RETURNING slot_no`).bind(id,now,editionKey,editionKey).first()}
async function releaseSlot(env,id){try{await env.GUARDIAN_DB.prepare(`UPDATE guardian_edition_slots SET order_id=NULL,reserved_at=NULL WHERE order_id=?`).bind(id).run()}catch{}}
async function queueRefund(env,row,provider,paymentReference,reason,now){const id=refundId(row.id);try{await env.GUARDIAN_DB.prepare(`INSERT OR IGNORE INTO guardian_refund_jobs (refund_job_id,guardian_id,provider,payment_reference,amount_usd,currency,reason,status,created_at,updated_at) VALUES (?,?,?,?,?,'USD',?,'pending',?,?)`).bind(id,row.id,provider||null,paymentReference||null,Number(row.price_usd),reason,now,now).run()}catch{}return id}
async function handleRefundEvent(env,{event,id,provider,eventId,paymentReference,amount,currency,receivedAt,body}){if(event!=='payment.refunded'&&event!=='payment.refund_failed')return null;if(!validId(id))return json({ok:false,error:'invalid_guardian_id'},400);let row;try{row=await env.GUARDIAN_DB.prepare('SELECT id,payment_status,issuance_status,refund_status FROM guardian_orders WHERE id=? LIMIT 1').bind(id).first()}catch{return json({ok:false,error:'storage_read_failed'},500)}if(!row)return json({ok:false,error:'not_found'},404);const providerRefundId=clean(body?.refundReference||body?.providerRefundId||paymentReference,160);if(event==='payment.refunded'){try{await env.GUARDIAN_DB.prepare(`UPDATE guardian_orders SET payment_status='refunded',refund_status='refunded',refund_reference=?,refunded_at=?,support_status=CASE WHEN issuance_status='sold_out_pending_refund' THEN 'resolved' ELSE support_status END WHERE id=?`).bind(providerRefundId||null,receivedAt,id).run();await env.GUARDIAN_DB.prepare(`UPDATE guardian_refund_jobs SET status='completed',provider_refund_id=?,updated_at=?,completed_at=? WHERE guardian_id=?`).bind(providerRefundId||null,receivedAt,receivedAt,id).run()}catch{return json({ok:false,error:'storage_write_failed'},500)}await logEvent(env,{eventId,provider,event,guardianId:id,paymentReference,amount,currency,status:'processed',receivedAt,processedAt:receivedAt});return json({ok:true,id,paymentStatus:'refunded',refundStatus:'refunded'})}const err=clean(body?.error||body?.errorCode||'provider_refund_failed',200);try{await env.GUARDIAN_DB.prepare(`UPDATE guardian_orders SET refund_status='failed',support_status='review' WHERE id=?`).bind(id).run();await env.GUARDIAN_DB.prepare(`UPDATE guardian_refund_jobs SET status='failed',last_error=?,updated_at=? WHERE guardian_id=?`).bind(err,receivedAt,id).run()}catch{return json({ok:false,error:'storage_write_failed'},500)}await logEvent(env,{eventId,provider,event,guardianId:id,paymentReference,amount,currency,status:'processed',receivedAt,processedAt:receivedAt,errorCode:err});return json({ok:true,id,refundStatus:'failed',supportStatus:'review'})}
async function handleTerminalPayment(env,{event,id,provider,eventId,paymentReference,amount,currency,receivedAt,body}){if(!['payment.cancelled','payment.failed','checkout.expired'].includes(event))return null;if(id&&!validId(id))return json({ok:false,error:'invalid_guardian_id'},400);const failureCode=clean(body?.errorCode||body?.error||event.replace('.','_'),120),checkoutStatus=event==='payment.cancelled'?'cancelled':event==='checkout.expired'?'expired':'failed';await updateCheckout(env,body,checkoutStatus,receivedAt,failureCode);if(id){try{await env.GUARDIAN_DB.prepare(`UPDATE guardian_orders SET payment_status=CASE WHEN payment_status='pending' THEN ? ELSE payment_status END,support_status=CASE WHEN ?='failed' AND payment_status='pending' THEN 'none' ELSE support_status END WHERE id=? AND issuance_status!='issued'`).bind(checkoutStatus==='cancelled'?'cancelled':checkoutStatus,checkoutStatus,id).run()}catch{return json({ok:false,error:'storage_write_failed'},500)}}await logEvent(env,{eventId,provider,event,guardianId:id,paymentReference,amount,currency,status:'processed',receivedAt,processedAt:receivedAt,errorCode:failureCode});return json({ok:true,id:id||null,paymentStatus:checkoutStatus,event})}
export async function onRequestPost({request,env}){
  if(env?.LUMEN_PAYMENTS_ENABLED!=='true')return json({ok:false,error:'payments_not_enabled'},503);
  if(!env?.GUARDIAN_DB)return json({ok:false,error:'storage_not_configured'},503);
  const supplied=request.headers.get('x-lumen-webhook-secret')||'';
  if(!env?.LUMEN_PAYMENT_WEBHOOK_SECRET||supplied!==env.LUMEN_PAYMENT_WEBHOOK_SECRET)return json({ok:false,error:'unauthorized'},401);
  const ct=request.headers.get('content-type')||'';if(!ct.toLowerCase().includes('application/json'))return json({ok:false,error:'content_type_required'},415);
  let body;try{body=await request.json()}catch{return json({ok:false,error:'invalid_json'},400)}
  const event=clean(body?.event,60),id=clean(body?.guardianId,40).toUpperCase(),paymentReference=clean(body?.paymentReference,120),provider=clean(body?.provider||'adapter',40).toLowerCase(),eventId=clean(body?.eventId||paymentReference||body?.checkoutId,160),currency=clean(body?.currency||'USD',8).toUpperCase(),amount=num(body?.amount),receivedAt=new Date().toISOString();
  if(!eventId)return json({ok:false,error:'event_id_required'},400);
  let handled=await handleRefundEvent(env,{event,id,provider,eventId,paymentReference,amount,currency,receivedAt,body});if(handled)return handled;
  handled=await handleTerminalPayment(env,{event,id,provider,eventId,paymentReference,amount,currency,receivedAt,body});if(handled)return handled;
  if(event!=='payment.succeeded'){await logEvent(env,{eventId,provider,event,guardianId:id,paymentReference,amount,currency,status:'ignored',receivedAt,processedAt:receivedAt});return json({ok:true,ignored:true,event:event||'unknown'});}
  if(!validId(id))return json({ok:false,error:'invalid_guardian_id'},400);
  if(!paymentReference)return json({ok:false,error:'payment_reference_required'},400);
  let row;try{row=await env.GUARDIAN_DB.prepare('SELECT id,tier,price_usd,edition_limit,edition_key,issuance_serial,payment_status,issuance_status,payment_reference,refund_status FROM guardian_orders WHERE id=? LIMIT 1').bind(id).first()}catch{return json({ok:false,error:'storage_read_failed'},500)}
  if(!row){await logEvent(env,{eventId,provider,event,guardianId:id,paymentReference,amount,currency,status:'rejected',receivedAt,processedAt:receivedAt,errorCode:'not_found'});return json({ok:false,error:'not_found'},404)}
  if(currency!=='USD'){await logEvent(env,{eventId,provider,event,guardianId:id,paymentReference,amount,currency,status:'rejected',receivedAt,processedAt:receivedAt,errorCode:'currency_mismatch'});return json({ok:false,error:'currency_mismatch'},409)}
  if(amount===null||Math.abs(amount-Number(row.price_usd))>0.0001){await logEvent(env,{eventId,provider,event,guardianId:id,paymentReference,amount,currency,status:'rejected',receivedAt,processedAt:receivedAt,errorCode:'amount_mismatch'});return json({ok:false,error:'amount_mismatch',expected:Number(row.price_usd)},409)}
  let duplicate=false;try{const old=await env.GUARDIAN_DB.prepare('SELECT event_id,status FROM guardian_payment_events WHERE event_id=? LIMIT 1').bind(eventId).first();duplicate=!!old}catch{}
  if(duplicate)return json({ok:true,id,status:row.issuance_status||'pending',refundStatus:row.refund_status||'none',idempotent:true,reason:'event_id'});
  const priorPayment=await processedPaymentReference(env,provider,paymentReference);
  if(priorPayment){if(priorPayment.guardian_id===id)return json({ok:true,id,status:row.issuance_status||'pending',refundStatus:row.refund_status||'none',idempotent:true,reason:'payment_reference'});try{await env.GUARDIAN_DB.prepare(`UPDATE guardian_orders SET support_status='review' WHERE id IN (?,?)`).bind(id,priorPayment.guardian_id).run()}catch{}await logEvent(env,{eventId,provider,event,guardianId:id,paymentReference,amount,currency,status:'rejected',receivedAt,processedAt:receivedAt,errorCode:'payment_reference_conflict'});return json({ok:false,error:'payment_reference_conflict',supportStatus:'review'},409)}
  if(row.payment_status==='paid'&&row.issuance_status==='issued'){await updateCheckout(env,body,'completed',receivedAt);await logEvent(env,{eventId,provider,event,guardianId:id,paymentReference,amount,currency,status:'processed',receivedAt,processedAt:receivedAt});return json({ok:true,id,status:'issued',serial:row.issuance_serial||null,idempotent:true})}
  const editionKey=clean(row.edition_key,80)||`${clean(row.tier,20)}-default`,limit=Math.max(1,Math.min(1000,Number(row.edition_limit)||1));let slot;
  try{slot=await claimSlot(env,editionKey,clean(row.tier,20),limit,id,receivedAt)}catch{return json({ok:false,error:'edition_reservation_failed'},500)}
  if(!slot){const refundJobId=await queueRefund(env,row,provider,paymentReference,'edition_sold_out_after_payment',receivedAt);try{await env.GUARDIAN_DB.prepare(`UPDATE guardian_orders SET payment_status='paid',issuance_status='sold_out_pending_refund',payment_reference=?,payment_provider=?,payment_event_id=?,paid_at=COALESCE(paid_at,?),refund_status='pending',refund_reason='edition_sold_out_after_payment',support_status='review' WHERE id=?`).bind(paymentReference||null,provider,eventId,receivedAt,id).run();await updateCheckout(env,body,'completed',receivedAt,'edition_sold_out_after_payment')}catch{return json({ok:false,error:'storage_write_failed'},500)}await logEvent(env,{eventId,provider,event,guardianId:id,paymentReference,amount,currency,status:'processed',receivedAt,processedAt:receivedAt,errorCode:'edition_sold_out_after_payment'});return json({ok:true,id,paymentStatus:'paid',issuanceStatus:'sold_out_pending_refund',refundStatus:'pending',refundJobId,supportStatus:'review'},202)}
  try{await env.GUARDIAN_DB.prepare(`UPDATE guardian_orders SET payment_status='paid',issuance_status='issued',payment_reference=?,payment_provider=?,payment_event_id=?,paid_at=COALESCE(paid_at,?),issued_at=COALESCE(issued_at,?),edition_key=?,issuance_serial=?,fulfillment_status='issued',refund_status='none',support_status='none' WHERE id=? AND payment_status!='refunded' AND issuance_status!='issued'`).bind(paymentReference||null,provider,eventId,receivedAt,receivedAt,editionKey,Number(slot.slot_no),id).run();await updateCheckout(env,body,'completed',receivedAt)}catch{await releaseSlot(env,id);return json({ok:false,error:'storage_write_failed'},500)}
  await logEvent(env,{eventId,provider,event,guardianId:id,paymentReference,amount,currency,status:'processed',receivedAt,processedAt:receivedAt});
  return json({ok:true,id,paymentStatus:'paid',issuanceStatus:'issued',editionKey,serial:Number(slot.slot_no),editionLimit:limit,issuedAt:receivedAt,verifyUrl:`/guardian-verify.html?id=${encodeURIComponent(id)}`});
}
export async function onRequest(){return json({ok:false,error:'method_not_allowed'},405,{Allow:'POST'})}
