import{calculateSaju,lunarToSolar}from'https://cdn.jsdelivr.net/npm/@fullstackfamily/manseryeok@1.0.8/+esm';

const ELEMENTS=['목','화','토','금','수'];
const STEM_ELEMENT={갑:'목',을:'목',병:'화',정:'화',무:'토',기:'토',경:'금',신:'금',임:'수',계:'수'};
const BRANCH_ELEMENT={자:'수',축:'토',인:'목',묘:'목',진:'토',사:'화',오:'화',미:'토',신:'금',유:'금',술:'토',해:'수'};
const LABEL={목:'성장 · 확장',화:'표현 · 추진',토:'안정 · 조율',금:'결단 · 질서',수:'유연 · 통찰'};
const FILTERS=[['all','전체'],['family','가족'],['partner','연인·배우자'],['friend','친구'],['work','직장·사업'],['other','기타']];
const GROUP_LABEL=Object.fromEntries(FILTERS);
const PARTNER=['아내','남편','배우자','연인','애인','여자친구','남자친구','약혼','와이프','허즈번드','wife','husband','partner','girlfriend','boyfriend'];
const FAMILY=['가족','부모','엄마','아빠','어머니','아버지','할머니','할아버지','형','누나','언니','오빠','동생','아들','딸','자녀','아이','사촌','삼촌','이모','고모','조카','며느리','사위','장모','장인','시어머니','시아버지','family','mother','father','sister','brother','son','daughter'];
const FRIEND=['친구','지인','동창','동문','선배','후배','친한','베프','friend'];
const WORK=['직장','회사','동료','상사','부하','팀장','대표','사장','직원','거래처','고객','사업','비즈니스','파트너사','협력','투자자','업무','work','coworker','colleague','boss','client','business'];
const PROFILE_KEY='lumen-connection-profile-v1',NETWORK_KEY='lumen-connection-network-web-v1';
const $=id=>document.getElementById(id);
let profile=read(PROFILE_KEY,null),network=read(NETWORK_KEY,[]),activeGroup='all',pending=null,selectedId=null;

function read(key,fallback){try{const value=JSON.parse(localStorage.getItem(key));return value??fallback}catch{return fallback}}
function write(key,value){localStorage.setItem(key,JSON.stringify(value))}
function esc(value=''){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function includesAny(value,words){const v=(value||'').trim().toLowerCase();return words.some(word=>v.includes(word.toLowerCase()))}
function inferGroup(relation){if(includesAny(relation,PARTNER))return'partner';if(includesAny(relation,FAMILY))return'family';if(includesAny(relation,WORK))return'work';if(includesAny(relation,FRIEND))return'friend';return'other'}
function memberGroup(member){return member.group||inferGroup(member.relation)}
function filtered(){return activeGroup==='all'?network:network.filter(m=>memberGroup(m)===activeGroup)}
function signed(n){return`${n>0?'+':''}${n}`}
function grade(score){return score>=80?'매우 강한 보완':score>=65?'좋은 보완':score>=45?'부분 보완':'보완 관찰'}
function calculateElements({birth,time,calendar,leap}){
 if(!birth)throw Error('생년월일을 입력해 주세요.');
 let[y,m,d]=birth.split('-').map(Number);if(!y||!m||!d)throw Error('생년월일을 확인해 주세요.');
 if(calendar==='lunar'){const converted=lunarToSolar(y,m,d,!!leap);y=converted.solar.year;m=converted.solar.month;d=converted.solar.day}
 let r;if(time){const[h,min]=time.split(':').map(Number);r=calculateSaju(y,m,d,h,min)}else r=calculateSaju(y,m,d);
 const pillars=[r.yearPillar,r.monthPillar,r.dayPillar,r.hourPillar||null];
 const counts={목:0,화:0,토:0,금:0,수:0};
 for(const p of pillars){if(!p)continue;const s=STEM_ELEMENT[p[0]],b=BRANCH_ELEMENT[p[1]];if(s)counts[s]++;if(b)counts[b]++}
 return counts;
}
function percent(counts,element){const total=ELEMENTS.reduce((sum,k)=>sum+(counts[k]||0),0)||1;return Math.round((counts[element]||0)/total*100)}
function percentages(counts){return Object.fromEntries(ELEMENTS.map(k=>[k,percent(counts,k)]))}
function complement(receiver,supplier){const r=percentages(receiver),s=percentages(supplier);return ELEMENTS.map(element=>{const need=Math.max(0,20-r[element])/100,supply=Math.max(0,s[element]-20)/100;return{element,matched:Math.min(need,supply)}}).sort((a,b)=>b.matched-a.matched)}
function connection(a,b){const aRec=complement(a.elements,b.elements),bRec=complement(b.elements,a.elements),gain=aRec.reduce((n,x)=>n+x.matched,0)+bRec.reduce((n,x)=>n+x.matched,0),score=Math.max(0,Math.min(100,Math.round(35+gain*325))),aTop=aRec.find(x=>x.matched>.005),bTop=bRec.find(x=>x.matched>.005);let summary=`두 사람의 오행 분포를 비교했을 때 ${grade(score)} 관계로 볼 수 있습니다.`;if(aTop)summary+=` ${b.name}님은 ${a.name}님의 ${aTop.element} 기운을 상대적으로 보완합니다.`;if(bTop)summary+=` ${a.name}님은 ${b.name}님의 ${bTop.element} 기운을 상대적으로 보완합니다.`;return{score,grade:grade(score),summary}}
function coverage(values){const list=ELEMENTS.map(k=>values[k]),spread=Math.max(...list)-Math.min(...list);return Math.max(0,Math.min(100,100-Math.round(spread*2.2)))}
function aggregate(me,members){const totals=Object.fromEntries(ELEMENTS.map(k=>[k,me[k]||0]));for(const m of members)for(const k of ELEMENTS)totals[k]+=(m.elements[k]||0);const total=ELEMENTS.reduce((sum,k)=>sum+totals[k],0)||1;return Object.fromEntries(ELEMENTS.map(k=>[k,Math.round(totals[k]/total*100)]))}
function networkSummary(members){if(!profile)return null;const personal=percentages(profile.elements),personalCoverage=coverage(personal),agg=aggregate(profile.elements,members),values=ELEMENTS.map(k=>agg[k]),min=Math.min(...values),max=Math.max(...values);return{aggregate:agg,coverage:coverage(agg),personalCoverage,delta:coverage(agg)-personalCoverage,weakest:ELEMENTS.filter(k=>agg[k]===min),strongest:ELEMENTS.filter(k=>agg[k]===max)}}
function memberImpact(members,id){if(!profile)return null;const member=members.find(m=>m.id===id);if(!member)return null;const beforeMembers=members.filter(m=>m.id!==id),before=aggregate(profile.elements,beforeMembers),after=aggregate(profile.elements,members),delta=Object.fromEntries(ELEMENTS.map(k=>[k,after[k]-before[k]]));return{before:coverage(before),after:coverage(after),coverageDelta:coverage(after)-coverage(before),elementDelta:delta}}
function groupCounts(){return Object.fromEntries(FILTERS.map(([id])=>[id,id==='all'?network.length:network.filter(m=>memberGroup(m)===id).length]))}
function inputData(prefix){return{name:$(prefix+'Name').value.trim(),birth:$(prefix+'Birth').value,time:$(prefix+'Time').value,calendar:$(prefix+'Calendar').value,leap:$(prefix+'Leap').checked}}
function setMessage(text,success=false){$('formMessage').textContent=text;$('formMessage').className='form-message'+(success?' success':'')}
function elementsHtml(elements){return ELEMENTS.map(k=>`<span>${k} ${percent(elements,k)}%</span>`).join('')}

function saveMyProfile(){try{const data=inputData('me');if(!data.name)throw Error('나의 이름 또는 닉네임을 입력해 주세요.');const elements=calculateElements(data);profile={name:data.name,elements,updatedAt:new Date().toISOString()};write(PROFILE_KEY,profile);renderProfile();renderAll();setMessage('나의 기준을 만들었습니다. 원본 생년월일과 출생시간은 저장하지 않았습니다.',true)}catch(e){setMessage(e.message||'나의 정보를 다시 확인해 주세요.')}}
function calculateOther(){try{const other=inputData('other');if(!other.name)throw Error('연결할 사람의 이름 또는 닉네임을 입력해 주세요.');if(!other.relation)throw Error('관계를 입력해 주세요.');let meProfile=profile;const me=inputData('me');if(me.birth){if(!me.name)throw Error('나의 이름 또는 닉네임을 입력해 주세요.');meProfile={name:me.name,elements:calculateElements(me)};profile=meProfile;write(PROFILE_KEY,profile);renderProfile()}if(!meProfile)throw Error('먼저 나의 오행 기준을 계산해 주세요.');const otherElements=calculateElements(other),pair=connection(meProfile,{name:other.name,elements:otherElements});pending={name:other.name,relation:other.relation,group:inferGroup(other.relation),elements:otherElements,score:pair.score,grade:pair.grade,summary:pair.summary};renderPair();setMessage('계산이 완료되었습니다. 출생정보 원본은 저장되지 않았습니다.',true)}catch(e){setMessage(e.message||'입력 정보를 확인해 주세요.')}}
function addPending(){if(!pending)return;const member={...pending,id:`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,addedAt:new Date().toISOString()};delete member.summary;network=[member,...network].slice(0,50);write(NETWORK_KEY,network);pending=null;$('pairResult').hidden=true;renderAll();setMessage(`${member.name}님을 인연지도에 추가했습니다.`,true)}
function deleteMember(id){network=network.filter(m=>m.id!==id);if(selectedId===id)selectedId=null;write(NETWORK_KEY,network);renderAll()}
function changeGroup(id,group){network=network.map(m=>m.id===id?{...m,group}:m);write(NETWORK_KEY,network);renderAll()}
function clearNetwork(){if(!network.length)return;if(!confirm('저장된 인연지도를 모두 초기화할까요? 나의 오행 기준은 유지됩니다.'))return;network=[];selectedId=null;write(NETWORK_KEY,network);renderAll()}

function renderProfile(){const el=$('profileSummary');if(!profile){$('profileStatus').textContent='기준 없음';$('profileStatus').className='status-pill';el.hidden=true;return}$('profileStatus').textContent='기준 준비됨';$('profileStatus').className='status-pill ready';if(!$('meName').value)$('meName').value=profile.name;el.hidden=false;el.innerHTML=`<strong>${esc(profile.name)}님의 저장된 오행 기준</strong><div class="mini-elements">${elementsHtml(profile.elements)}</div><small>생년월일·출생시간 원본은 저장하지 않습니다.</small>`}
function renderPair(){if(!pending){$('pairResult').hidden=true;return}$('pairResult').hidden=false;$('pairScore').textContent=pending.score;$('pairGrade').textContent=pending.grade;$('pairSummary').textContent=pending.summary;$('pairElements').innerHTML=ELEMENTS.map(k=>`<div class="element-box"><b>${k}</b><span>나 ${profile?percent(profile.elements,k):0}% · ${esc(pending.name)} ${percent(pending.elements,k)}%</span></div>`).join('');$('addToNetwork').textContent=`${pending.name}님을 내 인연지도에 추가`;requestAnimationFrame(()=>$('pairResult').scrollIntoView({behavior:'smooth',block:'nearest'}))}
function renderFilters(){const counts=groupCounts();$('relationFilters').innerHTML=FILTERS.map(([id,label])=>`<button type="button" class="filter-chip${activeGroup===id?' active':''}" data-filter="${id}">${label}<span>${counts[id]}</span></button>`).join('');$('relationFilters').querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{activeGroup=btn.dataset.filter;selectedId=null;renderAll()}))}
function renderMap(){const members=filtered(),map=$('networkMap');$('activeMapTitle').textContent=`${GROUP_LABEL[activeGroup]} 인연지도`;$('activeMapCount').textContent=`${members.length}명`;if(!members.length){map.innerHTML=`<div class="map-empty">${GROUP_LABEL[activeGroup]} 인연이 아직 없습니다.<br>새 인연을 추가하거나 다른 관계 필터를 선택해 주세요.</div>`;$('selectedPerson').hidden=true;return}const visible=[...members].sort((a,b)=>b.score-a.score).slice(0,6);let html=visible.map((m,i)=>`<span class="connector line-${i}"></span>`).join('');html+=`<div class="center-node"><strong>${esc(profile?.name||'나')}</strong><span>나</span></div>`;html+=visible.map((m,i)=>`<button type="button" class="node slot-${i}${selectedId===m.id?' active':''}" data-node="${esc(m.id)}"><strong>${esc(m.name)}</strong><small>${esc(m.relation)}</small><em>${m.score}</em></button>`).join('');if(members.length>6)html+=`<span class="more-badge">+${members.length-6}명</span>`;map.innerHTML=html;map.querySelectorAll('[data-node]').forEach(node=>node.addEventListener('click',()=>{selectedId=selectedId===node.dataset.node?null:node.dataset.node;renderMap();renderSelected()}));renderSelected()}
function renderSelected(){const box=$('selectedPerson'),members=filtered(),m=members.find(x=>x.id===selectedId);if(!m||!profile){box.hidden=true;return}const impact=memberImpact(members,m.id);box.hidden=false;box.innerHTML=`<div class="selected-head"><div><h3>${esc(m.name)}</h3><p>${esc(m.relation)} · ${GROUP_LABEL[memberGroup(m)]} · 보완도 ${m.score}</p></div><span class="selected-grade">${esc(m.grade)}</span></div><div class="impact-card"><strong>이 인연이 만든 변화</strong><div class="impact-score"><div><span>추가 전</span><b>${impact.before}</b></div><span>→</span><div><span>추가 후</span><b>${impact.after}</b></div><div class="delta-badge${impact.coverageDelta<0?' down':''}">${signed(impact.coverageDelta)}</div></div><div class="impact-chips">${ELEMENTS.map(k=>{const d=impact.elementDelta[k];return`<span class="${d>0?'up':d<0?'down':''}">${k} ${signed(d)}</span>`}).join('')}</div><p class="card-copy">${impact.coverageDelta>0?'현재 관계망의 오행 편차가 줄어 균형도가 높아졌습니다.':impact.coverageDelta<0?'현재 관계망의 오행 편차는 커졌지만, 이것은 관계의 좋고 나쁨이 아니라 구성 변화입니다.':'전체 균형 점수는 같지만 오행 구성에는 변화가 있습니다.'}</p></div>`}
function renderSummary(){const members=filtered(),box=$('networkSummary');if(!profile){box.innerHTML='<p class="map-empty">나의 오행 기준을 만들면 인연망 균형을 계산합니다.</p>';return}const s=networkSummary(members);box.innerHTML=`<div class="summary-metrics"><div class="summary-metric"><span>${GROUP_LABEL[activeGroup]} 인연</span><strong>${members.length}명</strong></div><div class="summary-metric"><span>관계망 균형도</span><strong>${s.coverage}</strong></div><div class="summary-metric"><span>부족한 기운</span><strong>${s.weakest.join('·')}</strong></div></div><div class="element-bars">${ELEMENTS.map(k=>`<div class="element-bar"><b>${k}</b><div class="element-track"><div class="element-fill" style="width:${s.aggregate[k]}%"></div></div><span>${s.aggregate[k]}%</span></div>`).join('')}</div><p class="card-copy">개인 기준 대비 균형 변화 ${signed(s.delta)}점 · 현재 ${s.weakest.join('·')} 기운이 상대적으로 낮습니다.</p>`}
function renderInsights(){const members=filtered(),title=$('impactTitle'),rank=$('contributionRanking'),a=$('compareA'),b=$('compareB');title.textContent=`${GROUP_LABEL[activeGroup]} 인연 영향 분석`;if(!profile||!members.length){rank.innerHTML='<div class="map-empty">선택한 관계군에 분석할 인연이 없습니다.</div>';fillCompare(a,[],'첫 번째 인연');fillCompare(b,[],'두 번째 인연');$('compareResult').textContent='인연을 두 명 이상 연결하면 비교할 수 있습니다.';$('compareGuide').textContent='두 사람을 선택하면 현재 부족한 오행을 누가 더 많이 가지고 있는지 비교합니다.';return}const ranking=members.map(m=>({m,i:memberImpact(members,m.id)})).sort((x,y)=>y.i.coverageDelta-x.i.coverageDelta||y.m.score-x.m.score).slice(0,3);rank.innerHTML=`<h3>${GROUP_LABEL[activeGroup]} · 균형 기여 TOP 3</h3>${ranking.map((x,index)=>`<div class="rank-row"><span class="rank-no">${index+1}</span><div class="rank-main"><strong>${esc(x.m.name)} · ${esc(x.m.relation)}</strong><span>보완도 ${x.m.score} · 균형 변화 ${signed(x.i.coverageDelta)}</span></div><span class="rank-delta${x.i.coverageDelta<0?' down':''}">${signed(x.i.coverageDelta)}</span></div>`).join('')}<p class="card-copy">균형 점수 변화 기준이며 음수도 관계의 좋고 나쁨을 뜻하지 않습니다.</p>`;const prevA=a.value,prevB=b.value;fillCompare(a,members,'첫 번째 인연',prevA);fillCompare(b,members,'두 번째 인연',prevB);const s=networkSummary(members);$('compareGuide').textContent=`비교 기준: 현재 ${GROUP_LABEL[activeGroup]} 인연망에서 상대적으로 부족한 ${s.weakest[0]} 기운`;renderCompare()}
function fillCompare(select,members,label,keep=''){select.innerHTML=`<option value="">${label}</option>`+members.map(m=>`<option value="${esc(m.id)}">${esc(m.name)} · ${esc(m.relation)}</option>`).join('');if(members.some(m=>m.id===keep))select.value=keep}
function renderCompare(){const members=filtered(),a=members.find(m=>m.id===$('compareA').value),b=members.find(m=>m.id===$('compareB').value),box=$('compareResult');if(!profile||!a||!b){box.textContent='서로 다른 인연 두 명을 선택해 주세요.';return}if(a.id===b.id){box.textContent='서로 다른 두 사람을 선택해 주세요.';return}const s=networkSummary(members),weak=s.weakest[0],av=percent(a.elements,weak),bv=percent(b.elements,weak);if(av===bv)box.innerHTML=`현재 부족한 <strong>${weak}</strong> 기운은 ${esc(a.name)}님과 ${esc(b.name)}님이 모두 ${av}%로 같습니다.`;else{const winner=av>bv?a:b,wv=Math.max(av,bv),lv=Math.min(av,bv);box.innerHTML=`현재 부족한 <strong>${weak}</strong> 기운 기준으로 <strong>${esc(winner.name)}님</strong>이 ${wv}%로 상대적으로 더 높습니다. 다른 인연은 ${lv}%입니다.<br><small>사람의 우열이 아니라 현재 관계망에서 부족한 오행 보유 비중만 비교합니다.</small>`}}
function renderPeople(){const members=filtered(),box=$('peopleList');if(!members.length){box.innerHTML=`<div class="map-empty">${GROUP_LABEL[activeGroup]} 인연이 없습니다.</div>`;return}box.innerHTML=members.map(m=>`<div class="person-row"><div class="person-top"><div class="person-main"><strong>${esc(m.name)} · ${esc(m.relation)}</strong><span>보완도 ${m.score} · ${esc(m.grade)} · 현재 분류 ${GROUP_LABEL[memberGroup(m)]}</span></div><div class="person-controls"><select class="group-select" data-group-id="${esc(m.id)}">${FILTERS.filter(([id])=>id!=='all').map(([id,label])=>`<option value="${id}"${memberGroup(m)===id?' selected':''}>${label}</option>`).join('')}</select><button type="button" class="delete-person" data-delete-id="${esc(m.id)}">삭제</button></div></div></div>`).join('');box.querySelectorAll('[data-group-id]').forEach(sel=>sel.addEventListener('change',()=>changeGroup(sel.dataset.groupId,sel.value)));box.querySelectorAll('[data-delete-id]').forEach(btn=>btn.addEventListener('click',()=>deleteMember(btn.dataset.deleteId)))}
function renderAll(){renderProfile();renderFilters();renderMap();renderSummary();renderInsights();renderPeople()}

$('saveProfile').addEventListener('click',saveMyProfile);
$('calculateConnection').addEventListener('click',calculateOther);
$('addToNetwork').addEventListener('click',addPending);
$('clearNetwork').addEventListener('click',clearNetwork);
$('compareA').addEventListener('change',renderCompare);
$('compareB').addEventListener('change',renderCompare);
['meCalendar','otherCalendar'].forEach(id=>$(id).addEventListener('change',()=>{const prefix=id.startsWith('me')?'me':'other';const lunar=$(id).value==='lunar';$(prefix+'Leap').disabled=!lunar;if(!lunar)$(prefix+'Leap').checked=false}));
$('meLeap').disabled=$('meCalendar').value!=='lunar';$('otherLeap').disabled=$('otherCalendar').value!=='lunar';
renderAll();
