(()=>{
'use strict';
const q=new URLSearchParams(location.search);
let lang=(q.get('lang')||localStorage.getItem('lumen-lang')||'ko').toLowerCase();
if(lang.startsWith('zh'))lang='zh';else if(lang.startsWith('ja'))lang='ja';else if(lang.startsWith('vi'))lang='vi';else if(lang.startsWith('tl')||lang.startsWith('fil'))lang='tl';else if(lang.startsWith('en'))lang='en';else lang='ko';
const C={
ko:{title:'루멘 명운 | Lumen Destiny',desc:'무료 사주·운세·궁합·인연지도 해설과 선택형 Lumen Guardian을 제공하는 문화·자기성찰 서비스',hero:'운명을 보는 것이 아니라,<br>삶의 방향을 찾습니다.',heroCopy:'사주와 운세 해설은 무료로 제공하고, 복잡한 명리 정보를 읽기 쉬운 말로 정리합니다.',free:'무료 사주',freeCopy:'기본 정보만 입력하면 만세력과 오행·십신·지장간·합충형파해를 결과 페이지에서 확인할 수 있습니다.',about:'본인',name:'이름을 입력하세요',gender:['남자','여자','선택하지 않음'],time:'모름 (태어난 시간)',calendar:['양력','음력'],leap:'음력 윤달로 입력',submit:'결과보기',privacy:'입력값은 결과 계산에만 사용하며 서버 DB에는 별도로 저장하지 않습니다.',services:'운세별 해설',servicesCopy:'한 번 입력한 사주 정보를 기반으로 각 주제에 맞는 해설을 단계적으로 제공합니다.',cards:[['금전운','재물과 소비·축적 성향을 오행과 십신 관점에서 정리하고, 돈을 다룰 때 유의할 패턴을 안내합니다.','내 사주로 보기 →'],['신년운세','한 해의 흐름을 원국과 세운의 관계로 살펴보고, 변화가 커지는 시기와 집중할 방향을 설명합니다.','내 사주로 보기 →'],['월간운세','이번 달에 드러나는 기운을 일·관계·재정의 관점으로 나눠 짧고 실용적으로 보여줍니다.','내 사주로 보기 →'],['오늘의 운세','오늘의 간지 흐름을 바탕으로 무리하지 말아야 할 부분과 활용하기 좋은 에너지를 한눈에 정리합니다.','내 사주로 보기 →'],['궁합','두 사람의 강점과 차이를 비교해 관계에서 잘 맞는 지점과 조율이 필요한 지점을 설명합니다.','두 사람 궁합 보기 →'],['인연지도','가족·연인·친구·직장 인연을 연결해 관계망의 오행 균형과 각 인연의 영향을 살펴봅니다.','나의 인연지도 만들기 →']],guardian:'소망을 담은 디지털 수호부적',guardianCopy:'모든 해설은 무료이며 부적은 원하는 분만 구매합니다. 개인 맞춤 부적과 수호동물, 고유번호, 발행일, QR 인증을 결합한 수집형 디지털 콘텐츠로 준비합니다.',archive:'부적 아카이브 보기',wishes:['합격 기원','승진 기원','취업 성공','재물 축적','건강 수호'],footer:['개인정보처리방침','이용약관','고객지원']},
en:{title:'Lumen Destiny | Free Saju & Connection Map',desc:'Free Saju, fortune, compatibility and Connection Map interpretations with optional Lumen Guardian digital collectibles.',hero:'Not to predict fate,<br>but to find your direction.',heroCopy:'Saju and fortune interpretations are free, with complex concepts explained in clear language.',free:'Free Saju',freeCopy:'Enter basic information to view the Four Pillars, Five Elements, Ten Gods, Hidden Stems and branch relations on the result page.',about:'About you',name:'Enter your name',gender:['Male','Female','Prefer not to say'],time:'Unknown (birth time)',calendar:['Solar calendar','Lunar calendar'],leap:'Lunar leap month',submit:'View Result',privacy:'Your inputs are used only for calculation and are not separately stored in a server database.',services:'Fortune Interpretations',servicesCopy:'Based on your Saju information, we provide interpretations for each topic step by step.',cards:[['Wealth','See wealth, spending and saving tendencies through the Five Elements and Ten Gods, with practical money patterns to watch.','View with my Saju →'],['New Year','Review the year through the relationship between your natal chart and annual flow, including periods of change and focus.','View with my Saju →'],['Monthly','See this month’s energy in concise, practical sections for work, relationships and finances.','View with my Saju →'],['Today','See at a glance what to avoid overdoing today and which energies are useful to apply.','View with my Saju →'],['Compatibility','Compare two people’s strengths and differences to see where you match and where adjustment may help.','View compatibility →'],['Connection Map','Connect family, partners, friends and work relationships to see how each connection changes your Five-Element network.','Build my connection map →']],guardian:'Digital Guardian for Your Wishes',guardianCopy:'All interpretations are free. Guardians are optional collectible digital content combining personalization, a guardian animal, serial number, issue date and QR verification.',archive:'View Guardian Archive',wishes:['Exam Success','Promotion','Career Success','Wealth','Wellness'],footer:['Privacy Policy','Terms of Use','Support']},
ja:{title:'ルーメン命運 | 四柱推命・ご縁マップ',desc:'無料の四柱推命・運勢・相性・ご縁マップと、希望者向けのLumen Guardianデジタルコレクション。',hero:'運命を当てるのではなく、<br>人生の方向を見つけます。',heroCopy:'四柱推命と運勢の解説は無料で、複雑な命理情報をわかりやすく整理します。',free:'無料四柱推命',freeCopy:'基本情報を入力すると、四柱・五行・十神・蔵干・地支の関係を結果ページで確認できます。',about:'本人',name:'名前を入力してください',gender:['男性','女性','選択しない'],time:'不明（出生時刻）',calendar:['新暦','旧暦'],leap:'旧暦の閏月',submit:'結果を見る',privacy:'入力情報は計算のみに使用し、サーバーDBには保存しません。',services:'運勢別解説',servicesCopy:'入力した四柱情報をもとに、各テーマの解説を段階的に提供します。',cards:[['金運','財運・消費・蓄財の傾向を五行と十神から整理し、お金を扱う際の注意点を案内します。','自分の四柱で見る →'],['新年運勢','命式と年運の関係から一年の流れを見て、変化が大きい時期と集中すべき方向を説明します。','自分の四柱で見る →'],['月間運勢','今月の気の流れを仕事・関係・財運に分けて短く実用的に示します。','自分の四柱で見る →'],['今日の運勢','今日の干支の流れから、無理を避ける点と活かしやすいエネルギーを整理します。','自分の四柱で見る →'],['相性','二人の強みと違いを比較し、合う点と調整が必要な点を説明します。','相性を見る →'],['ご縁マップ','家族・恋人・友人・仕事のご縁をつなぎ、関係ネットワークの五行バランスへの影響を見ます。','ご縁マップを作る →']],guardian:'願いを込めたデジタル守護符',guardianCopy:'すべての解説は無料です。Guardianは希望する方のみ購入でき、個別カスタマイズ、守護動物、固有番号、発行日、QR認証を組み合わせたコレクション型デジタルコンテンツです。',archive:'守護符アーカイブを見る',wishes:['合格祈願','昇進祈願','就職成功','財運蓄積','健康守護'],footer:['プライバシーポリシー','利用規約','サポート']},
tl:{title:'Lumen Destiny | Libreng Saju at Connection Map',desc:'Libreng Saju, kapalaran, compatibility at Connection Map, kasama ang opsyonal na Lumen Guardian digital collectibles.',hero:'Hindi para hulaan ang kapalaran,<br>kundi para hanapin ang direksiyon ng buhay.',heroCopy:'Libre ang Saju at mga paliwanag sa kapalaran, at ipinapaliwanag ang komplikadong konsepto sa madaling salita.',free:'Libreng Saju',freeCopy:'Ilagay ang pangunahing impormasyon upang makita ang Four Pillars, Five Elements, Ten Gods, Hidden Stems at branch relations.',about:'Ikaw',name:'Ilagay ang iyong pangalan',gender:['Lalaki','Babae','Ayaw tukuyin'],time:'Hindi alam (oras ng kapanganakan)',calendar:['Solar calendar','Lunar calendar'],leap:'Lunar leap month',submit:'Tingnan ang Resulta',privacy:'Ginagamit lamang ang impormasyon para sa pagkalkula at hindi hiwalay na iniimbak sa server database.',services:'Mga Paliwanag sa Kapalaran',servicesCopy:'Batay sa iyong Saju, nagbibigay kami ng paliwanag para sa bawat paksa.',cards:[['Pera','Tingnan ang ugali sa kita, gastos at ipon gamit ang Five Elements at Ten Gods.','Tingnan gamit ang aking Saju →'],['Bagong Taon','Tingnan ang daloy ng taon at mga panahong may malaking pagbabago at dapat pagtuunan.','Tingnan gamit ang aking Saju →'],['Buwanan','Makita ang enerhiya ngayong buwan para sa trabaho, relasyon at pananalapi.','Tingnan gamit ang aking Saju →'],['Ngayong Araw','Makita kung ano ang hindi dapat pilitin at anong enerhiya ang magandang gamitin ngayon.','Tingnan gamit ang aking Saju →'],['Compatibility','Ihambing ang lakas at pagkakaiba ng dalawang tao upang makita ang pagkakatugma at kailangang ayusin.','Tingnan ang compatibility →'],['Connection Map','Ikonekta ang pamilya, partner, kaibigan at trabaho upang makita ang balanse at epekto ng bawat ugnayan.','Gawin ang connection map →']],guardian:'Digital Guardian para sa Iyong Hiling',guardianCopy:'Libre ang lahat ng paliwanag. Opsyonal ang Guardian at pinagsasama nito ang personalization, guardian animal, serial number, issue date at QR verification.',archive:'Tingnan ang Guardian Archive',wishes:['Tagumpay sa Exam','Promosyon','Tagumpay sa Trabaho','Pagyaman','Kalusugan'],footer:['Patakaran sa Privacy','Mga Tuntunin','Suporta']},
vi:{title:'Lumen Destiny | Tứ Trụ và Bản đồ quan hệ',desc:'Luận giải Tứ Trụ, vận mệnh, tương hợp và Bản đồ quan hệ miễn phí, cùng Lumen Guardian tùy chọn.',hero:'Không phải để đoán số phận,<br>mà để tìm hướng đi cho cuộc sống.',heroCopy:'Phân tích Tứ Trụ và vận mệnh hoàn toàn miễn phí, với các khái niệm phức tạp được giải thích dễ hiểu.',free:'Tứ Trụ miễn phí',freeCopy:'Nhập thông tin cơ bản để xem Tứ Trụ, Ngũ Hành, Thập Thần, Tàng Can và quan hệ địa chi trên trang kết quả.',about:'Bản thân',name:'Nhập tên của bạn',gender:['Nam','Nữ','Không chọn'],time:'Không biết (giờ sinh)',calendar:['Dương lịch','Âm lịch'],leap:'Tháng nhuận âm lịch',submit:'Xem kết quả',privacy:'Thông tin chỉ được dùng để tính kết quả và không được lưu riêng trong cơ sở dữ liệu máy chủ.',services:'Luận giải theo chủ đề',servicesCopy:'Dựa trên thông tin Tứ Trụ đã nhập, chúng tôi cung cấp luận giải theo từng chủ đề.',cards:[['Tài lộc','Phân tích xu hướng tài lộc, chi tiêu và tích lũy theo Ngũ Hành và Thập Thần.','Xem bằng Tứ Trụ của tôi →'],['Vận năm mới','Xem dòng chảy của năm, thời điểm biến động lớn và hướng nên tập trung.','Xem bằng Tứ Trụ của tôi →'],['Vận tháng','Xem năng lượng tháng này theo công việc, quan hệ và tài chính một cách ngắn gọn.','Xem bằng Tứ Trụ của tôi →'],['Vận hôm nay','Tóm tắt điều nên tránh quá sức và nguồn năng lượng có thể tận dụng hôm nay.','Xem bằng Tứ Trụ của tôi →'],['Tương hợp','So sánh điểm mạnh và khác biệt của hai người để xem điểm hòa hợp và điều cần điều chỉnh.','Xem tương hợp →'],['Bản đồ quan hệ','Kết nối gia đình, người yêu, bạn bè và công việc để xem cân bằng Ngũ Hành và ảnh hưởng của từng mối quan hệ.','Tạo bản đồ quan hệ →']],guardian:'Guardian kỹ thuật số cho điều ước',guardianCopy:'Tất cả phần luận giải đều miễn phí. Guardian là nội dung sưu tầm tùy chọn kết hợp cá nhân hóa, linh vật bảo hộ, số sê-ri, ngày phát hành và xác minh QR.',archive:'Xem kho Guardian',wishes:['Cầu thi đỗ','Cầu thăng chức','Thành công nghề nghiệp','Tích lũy tài lộc','Bảo hộ sức khỏe'],footer:['Chính sách riêng tư','Điều khoản sử dụng','Hỗ trợ']},
zh:{title:'Lumen Destiny | 免费四柱与缘分地图',desc:'提供免费的四柱、运势、合婚与缘分地图解读，并提供可选的 Lumen Guardian 数字收藏内容。',hero:'不是为了断定命运，<br>而是为了找到人生方向。',heroCopy:'四柱与运势解读免费提供，并将复杂的命理信息整理成容易理解的语言。',free:'免费四柱',freeCopy:'输入基本信息后，可在结果页查看四柱、五行、十神、藏干以及地支关系。',about:'本人',name:'请输入姓名',gender:['男','女','不选择'],time:'不知道（出生时间）',calendar:['阳历','阴历'],leap:'阴历闰月',submit:'查看结果',privacy:'输入信息仅用于计算，不会单独保存到服务器数据库。',services:'分类运势解读',servicesCopy:'根据已输入的四柱信息，分主题逐步提供解读。',cards:[['财运','从五行与十神角度整理财富、消费与积累倾向，并提示理财时需要注意的模式。','用我的四柱查看 →'],['新年运势','从命局与流年的关系观察全年走势、变化较大的时期和应集中注意的方向。','用我的四柱查看 →'],['月运','将本月气运按工作、关系和财务分开，以简洁实用的方式呈现。','用我的四柱查看 →'],['今日运势','根据今日干支走势，整理不宜勉强之处以及适合利用的能量。','用我的四柱查看 →'],['合婚','比较两人的优势与差异，说明相合之处以及需要协调的部分。','查看两人合婚 →'],['缘分地图','连接家人、伴侣、朋友与职场关系，查看关系网络的五行平衡及每段缘分的影响。','创建我的缘分地图 →']],guardian:'承载愿望的数字守护符',guardianCopy:'所有解读均免费。Guardian 仅供有需要的用户选择购买，结合个性化、守护动物、唯一编号、发行日期与 QR 验证。',archive:'查看守护符档案',wishes:['考试顺利','升职祈愿','求职成功','财富积累','健康守护'],footer:['隐私政策','使用条款','客户支持']}
};
const T=C[lang]||C.ko;
const set=(sel,text,html=false)=>{const el=document.querySelector(sel);if(!el)return;if(html)el.innerHTML=text;else el.textContent=text};
const setOption=(sel,i,text)=>{const el=document.querySelector(sel);if(el?.options?.[i])el.options[i].textContent=text};
function apply(){
 document.documentElement.lang=lang==='zh'?'zh-CN':lang;localStorage.setItem('lumen-lang',lang);document.title=T.title;
 const md=document.querySelector('meta[name="description"]');if(md)md.content=T.desc;
 const ogd=document.querySelector('meta[property="og:description"]');if(ogd)ogd.content=T.desc;
 const twd=document.querySelector('meta[name="twitter:description"]');if(twd)twd.content=T.desc;
 set('.compact-hero h1',T.hero,true);set('.hero-copy',T.heroCopy);
 set('.form-heading h2',T.free);set('.form-heading>p:last-child',T.freeCopy);set('.group-title',T.about);
 const name=document.getElementById('userName');if(name)name.placeholder=T.name;
 T.gender.forEach((x,i)=>setOption('#gender',i,x));setOption('#birthTime',0,T.time);T.calendar.forEach((x,i)=>setOption('#calendarType',i,x));
 const leap=document.getElementById('leapMonthLabel');if(leap){const n=[...leap.childNodes].find(x=>x.nodeType===3);if(n)n.nodeValue=' '+T.leap;}
 set('#manseSubmit',T.submit);set('.privacy-note',T.privacy);set('.section-title h2',T.services);set('.section-title>p:last-child',T.servicesCopy);
 const cards=[...document.querySelectorAll('.fortune-service-card')];T.cards.forEach((c,i)=>{const card=cards[i];if(!card)return;const h=card.querySelector('h3'),p=card.querySelector('p'),a=card.querySelector('a');if(h)h.textContent=c[0];if(p)p.textContent=c[1];if(a){a.textContent=c[2];if(i<4)a.href='#analysis';else if(i===4)a.href=`/compatibility/?lang=${encodeURIComponent(lang)}`;else a.href=`/connection-map/?lang=${encodeURIComponent(lang)}`;}});
 document.querySelectorAll('a[href*="consult"]').forEach(a=>a.remove());
 set('#talisman h2',T.guardian);set('#talisman>div:first-child>p:not(.section-label)',T.guardianCopy);const arch=document.querySelector('#talisman a.button');if(arch)arch.textContent=T.archive;
 document.querySelectorAll('.talisman-mini-card strong').forEach((el,i)=>{if(T.wishes[i])el.textContent=T.wishes[i]});
 set('footer strong',lang==='ko'?'루멘 명운 · Lumen Destiny':lang==='ja'?'ルーメン命運 · Lumen Destiny':'Lumen Destiny');document.querySelectorAll('footer .footer-links a').forEach((a,i)=>{if(T.footer[i])a.textContent=T.footer[i]});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();
setTimeout(apply,80);setTimeout(apply,350);setTimeout(apply,900);
})();