(()=>{
const LANGS={ko:{flag:'🇰🇷',label:'한국어'},en:{flag:'🇺🇸',label:'English'},ja:{flag:'🇯🇵',label:'日本語'},tl:{flag:'🇵🇭',label:'Tagalog'},vi:{flag:'🇻🇳',label:'Tiếng Việt'}};
const ORDER=['ko','en','ja','tl','vi'];
const COUNTRY={KR:'ko',JP:'ja',PH:'tl',VN:'vi'};
const T={
en:{
'루멘 명운':'Lumen Destiny','무료 사주':'Free Saju','기능':'Services','디지털 부적':'Digital Guardian','부적 아카이브':'Guardian Archive','고객지원':'Support','다시 입력':'Enter Again','홈':'Home','개인정보처리방침':'Privacy Policy','이용약관':'Terms of Use',
'운명을 보는 것이 아니라,':'Not to predict fate,','삶의 방향을 찾습니다.':'but to find your direction.','사주·궁합·관상 정보와 해설은 무료입니다. 당신의 가능성을 이해하고 오늘의 방향을 찾아보세요.':'Saju, compatibility and face-reading information and interpretations are free. Understand your potential and find a direction for today.','무료 사주 시작하기':'Start Free Saju','서비스 알아보기':'Explore Services',
'나의 명운 알아보기':'Discover My Destiny','생년월일과 태어난 시간을 바탕으로 년주·월주·일주·시주와 오행 흐름을 결과 페이지에서 확인할 수 있습니다. 출생지는 입력하지 않아도 되도록 단순화했습니다.':'Enter your birth date and time to see the Four Pillars and Five Elements flow on the result page. Birthplace is not required.','이름 또는 별명':'Name or nickname','생년월일':'Date of birth','태어난 시간':'Time of birth','달력':'Calendar','양력':'Solar calendar','음력':'Lunar calendar','음력 윤달로 입력':'Lunar leap month','성별':'Gender','남성':'Male','여성':'Female','선택하지 않음':'Prefer not to say','정식 만세력 결과 보기':'View Manse Calendar Result','모르면 비워두세요. 시주는 ‘미입력’으로 표시됩니다.':'Leave blank if unknown. The hour pillar will be shown as not entered.','입력값은 결과 계산을 위해 결과 페이지 주소에 전달되며 서버 DB에는 별도로 저장하지 않습니다. 민감한 개인정보 입력은 최소화합니다.':'Inputs are passed to the result page for calculation and are not separately stored in a server database. Please minimize sensitive personal information.',
'루멘 명운의 주요 기능':'Lumen Destiny Services','무료 사주 분석':'Free Saju Analysis','년주·월주·일주·시주, 오행 균형과 성향을 이해하기 쉽게 안내합니다.':'Understand the Four Pillars, Five Elements balance and tendencies in clear language.','궁합과 관계 안내':'Compatibility & Relationships','두 사람의 장점과 차이를 살펴보고 더 나은 대화 방향을 제안합니다.':'Explore strengths and differences and get suggestions for better communication.','관상 해석':'Face Reading','사진 분석 후 원본을 보관하지 않는 구조로 준비합니다.':'Designed so uploaded originals are not retained after analysis.','루멘 AI':'Lumen AI','결과를 쉬운 말로 풀이하고 ‘오늘의 한 걸음’을 전합니다.':'Explains results in plain language and suggests one step for today.',
'소망을 담은 디지털 수호부적':'Digital Guardians for Your Wishes','모든 해설은 무료이며 부적은 원하는 분만 구매합니다. 개인 맞춤 부적 + 수호동물 + 고유번호 + 발행일 + QR 인증을 제공하는 수집형 디지털 콘텐츠로 준비하고 있습니다.':'All interpretations are free. Guardians are optional collectible digital content with personalization, guardian animal, serial number, issue date and QR verification.','부적은 특정 미래나 결과를 보장하지 않는 상징적 디지털 콘텐츠입니다.':'Guardians are symbolic digital content and do not guarantee a specific future or outcome.','지난 부적과 한정판 보기':'View Archive & Limited Editions','한정 Guardian 컬렉션':'Limited Guardian Collection','전체 아카이브 →':'Full archive →','판매 준비중':'Coming soon','발행 예정':'Planned release','아직 없음':'None yet','판매 완료 컬렉션':'Sold-out Collections','오늘의 선택이 내일의 운명을 만듭니다.':'Today’s choices shape tomorrow.','루멘 명운은 사람의 가능성과 선택을 믿습니다.':'Lumen Destiny believes in human potential and choice.',
'한 번 지나간 디자인은':'Once a design is gone,','다시 판매하지 않습니다.':'it will not be sold again.','소유 경험은 남기고,':'Keep the ownership experience,','과장된 약속은 만들지 않습니다.':'without exaggerated promises.','부적은 상징적 디지털 콘텐츠이며 특정 미래나 결과를 보장하지 않습니다.':'Guardians are symbolic digital content and do not guarantee a specific future or outcome.',
'고객지원':'Support','앱 이용, 계정, 결제 또는 개인정보 삭제 요청은 아래 이메일로 문의해 주세요.':'For app use, account, payment or personal-data deletion requests, contact us by email below.','개인정보처리방침':'Privacy Policy','루멘 명운은 서비스 제공에 필요한 최소한의 정보만 처리하는 것을 원칙으로 합니다.':'Lumen Destiny follows the principle of processing only the minimum information required to provide the service.','이용약관':'Terms of Use','루멘 명운의 사주·궁합·관상 해석은 전통문화 기반의 참고 콘텐츠이며 미래나 특정 결과를 보장하지 않습니다.':'Lumen Destiny interpretations are reference content based on traditional culture and do not guarantee the future or specific outcomes.',
'만세력 결과를 계산하고 있습니다.':'Calculating your Manse result.','한국 음력·절기 기준과 입력한 출생정보를 바탕으로 사주 네 기둥을 계산합니다.':'Calculating the Four Pillars using Korean lunar-calendar and solar-term standards with your birth information.','계산 엔진을 불러오는 중입니다…':'Loading calculation engine…','사주 네 기둥':'Four Pillars','절기 · 60갑자 · 진태양시 보정':'Solar terms · Sexagenary cycle','표면 오행 분포':'Five Elements Overview','기초 해설':'Basic Interpretation','다른 정보로 다시 보기':'Try Different Information','Lumen Guardian 보기':'View Lumen Guardian','년주':'Year','월주':'Month','일주':'Day','시주':'Hour','미입력':'Not entered','입력한 시각을 기준으로 시주를 계산했습니다.':'The hour pillar was calculated from the entered birth time.','출생시간을 입력하지 않아 시주는 표시하지 않습니다.':'The hour pillar is omitted because birth time was not entered.','가장 많이 보이는 오행':'Most prominent element','일간 · 나를 나타내는 천간':'Day Master · Heavenly Stem representing you','계산 기준':'Calculation basis','오늘의 한 걸음':'One Step Today','결과를 계산하지 못했습니다.':'Could not calculate the result.','입력 화면으로 돌아가기':'Return to input'
},
ja:{
'루멘 명운':'ルーメン命運','무료 사주':'無料四柱推命','기능':'サービス','디지털 부적':'デジタル守護符','부적 아카이브':'守護符アーカイブ','고객지원':'サポート','다시 입력':'再入力','홈':'ホーム','개인정보처리방침':'プライバシーポリシー','이용약관':'利用規約',
'운명을 보는 것이 아니라,':'運命を当てるのではなく、','삶의 방향을 찾습니다.':'人生の方向を見つけます。','사주·궁합·관상 정보와 해설은 무료입니다. 당신의 가능성을 이해하고 오늘의 방향을 찾아보세요.':'四柱推命・相性・人相の情報と解説は無料です。自分の可能性を理解し、今日の方向を見つけてください。','무료 사주 시작하기':'無料四柱推命を始める','서비스 알아보기':'サービスを見る','나의 명운 알아보기':'私の命運を知る','이름 또는 별명':'名前またはニックネーム','생년월일':'生年月日','태어난 시간':'出生時刻','달력':'暦','양력':'新暦','음력':'旧暦','음력 윤달로 입력':'旧暦の閏月','성별':'性別','남성':'男性','여성':'女性','선택하지 않음':'選択しない','정식 만세력 결과 보기':'万歳暦の結果を見る','모르면 비워두세요. 시주는 ‘미입력’으로 표시됩니다.':'不明な場合は空欄にしてください。時柱は未入力と表示されます。','루멘 명운의 주요 기능':'ルーメン命運の主な機能','무료 사주 분석':'無料四柱推命分析','궁합과 관계 안내':'相性と関係','관상 해석':'人相解釈','루멘 AI':'ルーメンAI','소망을 담은 디지털 수호부적':'願いを込めたデジタル守護符','부적은 특정 미래나 결과를 보장하지 않는 상징적 디지털 콘텐츠입니다.':'守護符は特定の未来や結果を保証するものではない象徴的なデジタルコンテンツです。','지난 부적과 한정판 보기':'過去の守護符と限定版を見る','한정 Guardian 컬렉션':'限定Guardianコレクション','전체 아카이브 →':'全アーカイブ →','판매 준비중':'準備中','발행 예정':'発行予定','아직 없음':'まだありません','오늘의 선택이 내일의 운명을 만듭니다.':'今日の選択が明日の運命をつくります。','루멘 명운은 사람의 가능성과 선택을 믿습니다.':'ルーメン命運は人の可能性と選択を信じます。','한 번 지나간 디자인은':'一度終了したデザインは','다시 판매하지 않습니다.':'再販売しません。','고객지원':'サポート','앱 이용, 계정, 결제 또는 개인정보 삭제 요청은 아래 이메일로 문의해 주세요.':'アプリ利用、アカウント、決済、個人情報削除のご依頼は以下のメールへお問い合わせください。','개인정보처리방침':'プライバシーポリシー','이용약관':'利用規約','만세력 결과를 계산하고 있습니다.':'万歳暦の結果を計算しています。','사주 네 기둥':'四柱','표면 오행 분포':'五行の分布','기초 해설':'基本解説','다른 정보로 다시 보기':'別の情報で見る','년주':'年柱','월주':'月柱','일주':'日柱','시주':'時柱','미입력':'未入力','가장 많이 보이는 오행':'最も多い五行','계산 기준':'計算基準','오늘의 한 걸음':'今日の一歩'
},
tl:{
'루멘 명운':'Lumen Destiny','무료 사주':'Libreng Saju','기능':'Mga Serbisyo','디지털 부적':'Digital Guardian','부적 아카이브':'Guardian Archive','고객지원':'Suporta','다시 입력':'Ilagay Muli','홈':'Home','개인정보처리방침':'Patakaran sa Privacy','이용약관':'Mga Tuntunin',
'운명을 보는 것이 아니라,':'Hindi para hulaan ang kapalaran,','삶의 방향을 찾습니다.':'kundi para hanapin ang direksiyon ng buhay.','사주·궁합·관상 정보와 해설은 무료입니다. 당신의 가능성을 이해하고 오늘의 방향을 찾아보세요.':'Libre ang impormasyon at paliwanag sa Saju, compatibility at face reading. Unawain ang iyong potensyal at hanapin ang direksiyon para sa araw na ito.','무료 사주 시작하기':'Simulan ang Libreng Saju','서비스 알아보기':'Tingnan ang Serbisyo','나의 명운 알아보기':'Alamin ang Aking Destiny','이름 또는 별명':'Pangalan o palayaw','생년월일':'Petsa ng kapanganakan','태어난 시간':'Oras ng kapanganakan','달력':'Kalendaryo','양력':'Solar','음력':'Lunar','음력 윤달로 입력':'Lunar leap month','성별':'Kasarian','남성':'Lalaki','여성':'Babae','선택하지 않음':'Ayaw tukuyin','정식 만세력 결과 보기':'Tingnan ang Manse Result','모르면 비워두세요. 시주는 ‘미입력’으로 표시됩니다.':'Iwanang blangko kung hindi alam.','루멘 명운의 주요 기능':'Mga Pangunahing Serbisyo','무료 사주 분석':'Libreng Saju Analysis','궁합과 관계 안내':'Compatibility at Relasyon','관상 해석':'Face Reading','루멘 AI':'Lumen AI','소망을 담은 디지털 수호부적':'Digital Guardian para sa Iyong Hiling','부적은 특정 미래나 결과를 보장하지 않는 상징적 디지털 콘텐츠입니다.':'Ang Guardian ay simbolikong digital content at hindi garantiya ng tiyak na kinabukasan o resulta.','지난 부적과 한정판 보기':'Tingnan ang Archive','한정 Guardian 컬렉션':'Limited Guardian Collection','전체 아카이브 →':'Buong archive →','판매 준비중':'Malapit na','발행 예정':'Planong ilabas','아직 없음':'Wala pa','오늘의 선택이 내일의 운명을 만듭니다.':'Ang mga pili ngayon ang humuhubog sa bukas.','고객지원':'Suporta','앱 이용, 계정, 결제 또는 개인정보 삭제 요청은 아래 이메일로 문의해 주세요.':'Para sa app, account, bayad o pagtanggal ng personal data, mag-email sa ibaba.','개인정보처리방침':'Patakaran sa Privacy','이용약관':'Mga Tuntunin','만세력 결과를 계산하고 있습니다.':'Kinakalkula ang iyong Manse result.','사주 네 기둥':'Apat na Haligi','표면 오행 분포':'Limang Elemento','기초 해설':'Pangunahing Paliwanag','다른 정보로 다시 보기':'Subukan ang Ibang Impormasyon','년주':'Taon','월주':'Buwan','일주':'Araw','시주':'Oras','미입력':'Hindi inilagay','가장 많이 보이는 오행':'Pinakamalinaw na elemento','계산 기준':'Batayan ng kalkulasyon','오늘의 한 걸음':'Isang Hakbang Ngayon'
},
vi:{
'루멘 명운':'Lumen Destiny','무료 사주':'Tứ trụ miễn phí','기능':'Dịch vụ','디지털 부적':'Bùa hộ mệnh số','부적 아카이브':'Kho Guardian','고객지원':'Hỗ trợ','다시 입력':'Nhập lại','홈':'Trang chủ','개인정보처리방침':'Chính sách riêng tư','이용약관':'Điều khoản sử dụng',
'운명을 보는 것이 아니라,':'Không phải để đoán định số phận,','삶의 방향을 찾습니다.':'mà để tìm hướng đi cho cuộc sống.','사주·궁합·관상 정보와 해설은 무료입니다. 당신의 가능성을 이해하고 오늘의 방향을 찾아보세요.':'Thông tin và diễn giải Tứ trụ, hợp duyên và nhân tướng đều miễn phí. Hãy hiểu tiềm năng của bạn và tìm hướng đi cho hôm nay.','무료 사주 시작하기':'Bắt đầu Tứ trụ miễn phí','서비스 알아보기':'Xem dịch vụ','나의 명운 알아보기':'Khám phá vận mệnh của tôi','이름 또는 별명':'Tên hoặc biệt danh','생년월일':'Ngày sinh','태어난 시간':'Giờ sinh','달력':'Lịch','양력':'Dương lịch','음력':'Âm lịch','음력 윤달로 입력':'Tháng nhuận âm lịch','성별':'Giới tính','남성':'Nam','여성':'Nữ','선택하지 않음':'Không chọn','정식 만세력 결과 보기':'Xem kết quả Vạn niên lịch','모르면 비워두세요. 시주는 ‘미입력’으로 표시됩니다.':'Nếu không biết, hãy để trống. Trụ giờ sẽ hiển thị chưa nhập.','루멘 명운의 주요 기능':'Các dịch vụ chính','무료 사주 분석':'Phân tích Tứ trụ miễn phí','궁합과 관계 안내':'Tương hợp & Quan hệ','관상 해석':'Nhân tướng','루멘 AI':'Lumen AI','소망을 담은 디지털 수호부적':'Guardian số cho điều ước của bạn','부적은 특정 미래나 결과를 보장하지 않는 상징적 디지털 콘텐츠입니다.':'Guardian là nội dung số mang tính biểu tượng và không đảm bảo một tương lai hay kết quả cụ thể.','지난 부적과 한정판 보기':'Xem kho & bản giới hạn','한정 Guardian 컬렉션':'Bộ sưu tập Guardian giới hạn','전체 아카이브 →':'Toàn bộ kho →','판매 준비중':'Sắp ra mắt','발행 예정':'Dự kiến phát hành','아직 없음':'Chưa có','오늘의 선택이 내일의 운명을 만듭니다.':'Lựa chọn hôm nay tạo nên ngày mai.','고객지원':'Hỗ trợ','앱 이용, 계정, 결제 또는 개인정보 삭제 요청은 아래 이메일로 문의해 주세요.':'Về ứng dụng, tài khoản, thanh toán hoặc yêu cầu xóa dữ liệu cá nhân, vui lòng liên hệ email bên dưới.','개인정보처리방침':'Chính sách riêng tư','이용약관':'Điều khoản sử dụng','만세력 결과를 계산하고 있습니다.':'Đang tính kết quả Vạn niên lịch.','사주 네 기둥':'Bốn Trụ','표면 오행 분포':'Phân bố Ngũ hành','기초 해설':'Diễn giải cơ bản','다른 정보로 다시 보기':'Xem với thông tin khác','년주':'Trụ năm','월주':'Trụ tháng','일주':'Trụ ngày','시주':'Trụ giờ','미입력':'Chưa nhập','가장 많이 보이는 오행':'Ngũ hành nổi bật nhất','계산 기준':'Cơ sở tính toán','오늘의 한 걸음':'Một bước hôm nay'
}};
const originalText=new WeakMap();
function translateDynamic(text,lang){if(lang==='ko')return text;let m=text.match(/^(.+)님의 만세력 결과$/);if(m){return lang==='ja'?`${m[1]}さんの万歳暦結果`:lang==='tl'?`Manse Result ni ${m[1]}`:lang==='vi'?`Kết quả Vạn niên lịch của ${m[1]}`:`${m[1]}'s Manse Result`;}
m=text.match(/^기준 양력 (\d+)년 (\d+)월 (\d+)일(.*)$/);if(m){const tail=m[4]||'';return lang==='ja'?`基準日 ${m[1]}年${m[2]}月${m[3]}日${tail}`:lang==='tl'?`Batayang petsa ${m[1]}-${m[2]}-${m[3]}${tail}`:lang==='vi'?`Ngày chuẩn ${m[3]}/${m[2]}/${m[1]}${tail}`:`Reference date ${m[1]}-${m[2]}-${m[3]}${tail}`;}
return T[lang]?.[text]||text;}
function walk(root,lang){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{if(n.parentElement?.closest('.language-switcher'))return;const raw=originalText.has(n)?originalText.get(n):n.nodeValue;if(!originalText.has(n))originalText.set(n,raw);const lead=raw.match(/^\s*/)?.[0]||'',trail=raw.match(/\s*$/)?.[0]||'',core=raw.trim();if(core)n.nodeValue=lead+translateDynamic(core,lang)+trail;});document.querySelectorAll('input[placeholder]').forEach(el=>{if(!el.dataset.i18nPlaceholder)el.dataset.i18nPlaceholder=el.placeholder;el.placeholder=translateDynamic(el.dataset.i18nPlaceholder,lang);});}
function setLang(lang,persist=true){if(!LANGS[lang])lang='en';document.documentElement.lang=lang==='tl'?'fil':lang;document.body.dataset.lang=lang;if(persist)localStorage.setItem('lumen-language',lang);walk(document.body,lang);document.querySelectorAll('.language-switcher button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));window.LumenI18n.current=lang;window.LumenI18n.t=(s)=>translateDynamic(s,lang);document.dispatchEvent(new CustomEvent('lumen-language-change',{detail:{lang}}));}
function inject(){if(document.querySelector('.language-switcher'))return;const bar=document.createElement('div');bar.className='language-switcher';bar.setAttribute('aria-label','Language selector');ORDER.forEach(code=>{const b=document.createElement('button');b.type='button';b.dataset.lang=code;b.title=LANGS[code].label;b.setAttribute('aria-label',LANGS[code].label);b.textContent=LANGS[code].flag;b.addEventListener('click',()=>setLang(code,true));bar.appendChild(b);});const header=document.querySelector('.site-header');if(header)header.insertAdjacentElement('afterend',bar);else document.body.prepend(bar);const style=document.createElement('style');style.textContent=`.language-switcher{width:min(920px,calc(100% - 32px));margin:14px auto 20px;display:grid;grid-template-columns:repeat(5,1fr);border:1.5px solid #ff5d57;border-radius:16px;overflow:hidden;background:#fff;box-shadow:0 5px 18px rgba(31,41,55,.05)}.language-switcher button{height:48px;border:0;border-right:1px solid #ece7df;background:#fff;font-size:23px;cursor:pointer;transition:.16s}.language-switcher button:last-child{border-right:0}.language-switcher button:hover{background:#fff3f1}.language-switcher button.active{background:#ff5d57}.language-switcher button:focus-visible{outline:3px solid #22335b;outline-offset:-3px}@media(max-width:680px){.language-switcher{margin:10px auto 14px;width:calc(100% - 24px);border-radius:13px}.language-switcher button{height:43px;font-size:21px}}`;document.head.appendChild(style);}
async function detect(){const saved=localStorage.getItem('lumen-language');if(saved&&LANGS[saved])return saved;try{const r=await fetch('/cdn-cgi/trace',{cache:'no-store'});const txt=await r.text();const loc=(txt.match(/^loc=([A-Z]{2})$/m)||[])[1];if(loc)return COUNTRY[loc]||'en';}catch(e){}const n=(navigator.language||'en').toLowerCase();if(n.startsWith('ko'))return'ko';if(n.startsWith('ja'))return'ja';if(n.startsWith('tl')||n.startsWith('fil'))return'tl';if(n.startsWith('vi'))return'vi';return'en';}
window.LumenI18n={current:'ko',t:s=>s,set:setLang};
async function init(){inject();const lang=await detect();setLang(lang,false);const obs=new MutationObserver(ms=>{const l=window.LumenI18n.current;ms.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType===1)walk(n,l);else if(n.nodeType===3&&n.parentElement)walk(n.parentElement,l);}));});obs.observe(document.body,{childList:true,subtree:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();