(()=>{
const ORDER=['ko','en','ja','tl','vi'];
const LANGS={ko:['🇰🇷','한국어'],en:['🇺🇸','English'],ja:['🇯🇵','日本語'],tl:['🇵🇭','Tagalog'],vi:['🇻🇳','Tiếng Việt']};
const COUNTRY={KR:'ko',JP:'ja',PH:'tl',VN:'vi'};
const B={
'루멘 명운':{en:'Lumen Destiny',ja:'ルーメン命運',tl:'Lumen Destiny',vi:'Lumen Destiny'},
'무료사주':{en:'Free Saju',ja:'無料四柱推命',tl:'Libreng Saju',vi:'Tử vi miễn phí'},'금전운':{en:'Wealth',ja:'金運',tl:'Pera',vi:'Tài lộc'},'신년운세':{en:'New Year',ja:'新年運勢',tl:'Bagong Taon',vi:'Vận năm mới'},'월간운세':{en:'Monthly',ja:'月間運勢',tl:'Buwanan',vi:'Vận tháng'},'오늘의 운세':{en:'Today',ja:'今日の運勢',tl:'Ngayong Araw',vi:'Vận hôm nay'},'궁합':{en:'Compatibility',ja:'相性',tl:'Compatibility',vi:'Tương hợp'},'1:1상담':{en:'1:1 Consultation',ja:'1:1相談',tl:'1:1 Konsultasyon',vi:'Tư vấn 1:1'},
'운명을 보는 것이 아니라,':{en:'Not to predict fate,',ja:'運命を当てるのではなく、',tl:'Hindi para hulaan ang kapalaran,',vi:'Không phải để đoán số phận,'},'삶의 방향을 찾습니다.':{en:'but to find your direction.',ja:'人生の方向を見つけます。',tl:'kundi para hanapin ang direksiyon ng buhay.',vi:'mà để tìm hướng đi cho cuộc sống.'},
'사주와 운세 해설은 무료로 제공하고, 복잡한 명리 정보를 읽기 쉬운 말로 정리합니다.':{en:'Saju and fortune interpretations are free, with complex concepts explained in clear language.',ja:'四柱推命と運勢の解説は無料で、複雑な命理情報をわかりやすく整理します。',tl:'Libre ang Saju at mga paliwanag sa kapalaran, at ipinapaliwanag ang komplikadong konsepto sa madaling salita.',vi:'Phân tích Tứ Trụ và vận mệnh hoàn toàn miễn phí, với các khái niệm phức tạp được giải thích dễ hiểu.'},
'무료 사주':{en:'Free Saju',ja:'無料四柱推命',tl:'Libreng Saju',vi:'Tử vi miễn phí'},'기본 정보만 입력하면 만세력과 오행·십신·지장간·합충형파해를 결과 페이지에서 확인할 수 있습니다.':{en:'Enter basic information to view the Four Pillars, Five Elements, Ten Gods, Hidden Stems and branch relations on the result page.',ja:'基本情報を入力すると、四柱・五行・十神・蔵干・支の関係を結果ページで確認できます。',tl:'Ilagay ang pangunahing impormasyon upang makita ang Four Pillars, Five Elements, Ten Gods, Hidden Stems at branch relations.',vi:'Nhập thông tin cơ bản để xem Tứ Trụ, Ngũ Hành, Thập Thần, Tàng Can và quan hệ địa chi trên trang kết quả.'},
'본인':{en:'About you',ja:'本人',tl:'Ikaw',vi:'Bản thân'},'이름을 입력하세요':{en:'Enter your name',ja:'名前を入力してください',tl:'Ilagay ang iyong pangalan',vi:'Nhập tên của bạn'},'남자':{en:'Male',ja:'男性',tl:'Lalaki',vi:'Nam'},'여자':{en:'Female',ja:'女性',tl:'Babae',vi:'Nữ'},'선택하지 않음':{en:'Prefer not to say',ja:'選択しない',tl:'Ayaw tukuyin',vi:'Không chọn'},'모름 (태어난 시간)':{en:'Unknown (birth time)',ja:'不明（出生時刻）',tl:'Hindi alam (oras ng kapanganakan)',vi:'Không biết (giờ sinh)'},'양력':{en:'Solar calendar',ja:'新暦',tl:'Solar calendar',vi:'Dương lịch'},'음력':{en:'Lunar calendar',ja:'旧暦',tl:'Lunar calendar',vi:'Âm lịch'},'음력 윤달로 입력':{en:'Lunar leap month',ja:'旧暦の閏月',tl:'Lunar leap month',vi:'Tháng nhuận âm lịch'},'결과보기':{en:'View Result',ja:'結果を見る',tl:'Tingnan ang Resulta',vi:'Xem kết quả'},
'입력값은 결과 계산에만 사용하며 서버 DB에는 별도로 저장하지 않습니다.':{en:'Your inputs are used only for calculation and are not separately stored in a server database.',ja:'入力情報は計算のみに使用し、サーバーDBには保存しません。',tl:'Ginagamit lamang ang impormasyon para sa pagkalkula at hindi hiwalay na iniimbak sa server database.',vi:'Thông tin chỉ được dùng để tính kết quả và không được lưu riêng trong cơ sở dữ liệu máy chủ.'},
'운세별 해설':{en:'Fortune Interpretations',ja:'運勢別解説',tl:'Mga Paliwanag sa Kapalaran',vi:'Luận giải theo chủ đề'},'한 번 입력한 사주 정보를 기반으로 각 주제에 맞는 해설을 단계적으로 제공합니다.':{en:'Based on your Saju information, we provide interpretations for each topic step by step.',ja:'入力した四柱情報をもとに、各テーマの解説を段階的に提供します。',tl:'Batay sa iyong Saju, nagbibigay kami ng paliwanag para sa bawat paksa.',vi:'Dựa trên thông tin Tứ Trụ đã nhập, chúng tôi cung cấp luận giải theo từng chủ đề.'},
'재물과 소비·축적 성향을 오행과 십신 관점에서 정리하고, 돈을 다룰 때 유의할 패턴을 안내합니다.':{en:'See wealth, spending and saving tendencies through the Five Elements and Ten Gods, with practical money patterns to watch.',ja:'財運・消費・蓄財の傾向を五行と十神から整理し、お金を扱う際の注意点を案内します。',tl:'Tingnan ang ugali sa kita, gastos at ipon gamit ang Five Elements at Ten Gods.',vi:'Phân tích xu hướng tài lộc, chi tiêu và tích lũy theo Ngũ Hành và Thập Thần.'},
'한 해의 흐름을 원국과 세운의 관계로 살펴보고, 변화가 커지는 시기와 집중할 방향을 설명합니다.':{en:'Review the year through the relationship between your natal chart and annual flow, including periods of change and focus.',ja:'命式と年運の関係から一年の流れを見て、変化が大きい時期と集中すべき方向を説明します。',tl:'Tingnan ang daloy ng taon at mga panahong may malaking pagbabago at dapat pagtuunan.',vi:'Xem dòng chảy của năm, thời điểm biến động lớn và hướng nên tập trung.'},
'이번 달에 드러나는 기운을 일·관계·재정의 관점으로 나눠 짧고 실용적으로 보여줍니다.':{en:'See this month’s energy in concise, practical sections for work, relationships and finances.',ja:'今月の気の流れを仕事・関係・財運に分けて短く実用的に示します。',tl:'Makita ang enerhiya ngayong buwan para sa trabaho, relasyon at pananalapi.',vi:'Xem năng lượng tháng này theo công việc, quan hệ và tài chính một cách ngắn gọn, thực tế.'},
'오늘의 간지 흐름을 바탕으로 무리하지 말아야 할 부분과 활용하기 좋은 에너지를 한눈에 정리합니다.':{en:'See at a glance what to avoid overdoing today and which energies are useful to apply.',ja:'今日の干支の流れから、無理を避ける点と活かしやすいエネルギーを整理します。',tl:'Makita kung ano ang hindi dapat pilitin at anong enerhiya ang magandang gamitin ngayon.',vi:'Tóm tắt điều nên tránh quá sức và nguồn năng lượng nên tận dụng hôm nay.'},
'두 사람의 강점과 차이를 비교해 관계에서 잘 맞는 지점과 조율이 필요한 지점을 설명합니다.':{en:'Compare two people’s strengths and differences to see where you match and where adjustment may help.',ja:'二人の強みと違いを比較し、相性の良い点と調整が必要な点を説明します。',tl:'Ihambing ang lakas at pagkakaiba ng dalawang tao upang makita ang pagkakatugma at kailangang ayusin.',vi:'So sánh điểm mạnh và khác biệt của hai người để thấy điểm hợp và điểm cần điều chỉnh.'},
'결과를 읽다가 궁금한 내용을 루멘 AI에게 질문하고, 자신의 상황에 맞춰 해설을 이어가는 기능으로 확장합니다.':{en:'Ask Lumen AI follow-up questions about your result and continue with interpretations tailored to your situation.',ja:'結果についてルーメンAIに質問し、自分の状況に合わせて解説を続けられます。',tl:'Magtanong sa Lumen AI tungkol sa resulta at ipagpatuloy ang paliwanag ayon sa iyong sitwasyon.',vi:'Hỏi Lumen AI về kết quả và tiếp tục nhận luận giải phù hợp với hoàn cảnh của bạn.'},'내 사주로 보기 →':{en:'View with my Saju →',ja:'自分の四柱で見る →',tl:'Tingnan gamit ang aking Saju →',vi:'Xem bằng Tứ Trụ của tôi →'},'기본 사주부터 보기 →':{en:'Start with basic Saju →',ja:'基本四柱から見る →',tl:'Magsimula sa basic Saju →',vi:'Bắt đầu với Tứ Trụ cơ bản →'},
'소망을 담은 디지털 수호부적':{en:'Digital Guardian for Your Wishes',ja:'願いを込めたデジタル守護符',tl:'Digital Guardian para sa Iyong Hiling',vi:'Bùa hộ mệnh kỹ thuật số cho điều ước'},
'모든 해설은 무료이며 부적은 원하는 분만 구매합니다. 개인 맞춤 부적과 수호동물, 고유번호, 발행일, QR 인증을 결합한 수집형 디지털 콘텐츠로 준비합니다.':{en:'All interpretations are free. Guardians are optional collectible digital content combining personalization, a guardian animal, serial number, issue date and QR verification.',ja:'すべての解説は無料です。守護符は希望する方のみ購入でき、個別カスタマイズ、守護動物、固有番号、発行日、QR認証を組み合わせたコレクション型デジタルコンテンツです。',tl:'Libre ang lahat ng paliwanag. Opsyonal ang Guardian at may personalization, guardian animal, serial number, issue date at QR verification.',vi:'Tất cả phần luận giải đều miễn phí. Bùa hộ mệnh là nội dung số sưu tầm tùy chọn, kết hợp cá nhân hóa, linh vật bảo hộ, số sê-ri, ngày phát hành và xác thực QR.'},
'부적은 특정 미래나 결과를 보장하지 않는 상징적 디지털 콘텐츠입니다.':{en:'Guardians are symbolic digital content and do not guarantee a specific future or outcome.',ja:'守護符は特定の未来や結果を保証するものではない象徴的なデジタルコンテンツです。',tl:'Ang Guardian ay simbolikong digital content at hindi garantiya ng partikular na hinaharap o resulta.',vi:'Bùa hộ mệnh là nội dung số mang tính biểu tượng và không bảo đảm một tương lai hay kết quả cụ thể.'},'부적 아카이브 보기':{en:'View Guardian Archive',ja:'守護符アーカイブを見る',tl:'Tingnan ang Guardian Archive',vi:'Xem kho bùa hộ mệnh'},'부적 아카이브':{en:'Guardian Archive',ja:'守護符アーカイブ',tl:'Guardian Archive',vi:'Kho bùa hộ mệnh'},
'Guardian 기본 · 디자인당 100개':{en:'Basic Guardian · 100 per design',ja:'Basic Guardian · 各デザイン100個',tl:'Basic Guardian · 100 bawat disenyo',vi:'Guardian cơ bản · 100 mỗi thiết kế'},'개인 소망 맞춤 · 디자인당 100개':{en:'Personal Wish · 100 per design',ja:'個人願望カスタム · 各デザイン100個',tl:'Personal Wish · 100 bawat disenyo',vi:'Cá nhân hóa điều ước · 100 mỗi thiết kế'},'Rare Edition · 디자인당 5개':{en:'Rare Edition · 5 per design',ja:'Rare Edition · 各デザイン5個',tl:'Rare Edition · 5 bawat disenyo',vi:'Rare Edition · 5 mỗi thiết kế'},'Legendary Motion · 단 1개':{en:'Legendary Motion · Only 1',ja:'Legendary Motion · 1個限定',tl:'Legendary Motion · 1 lamang',vi:'Legendary Motion · chỉ 1'},
'루멘 명운 · Lumen Destiny':{en:'Lumen Destiny',ja:'ルーメン命運 · Lumen Destiny',tl:'Lumen Destiny',vi:'Lumen Destiny'},'개인정보처리방침':{en:'Privacy Policy',ja:'プライバシーポリシー',tl:'Patakaran sa Privacy',vi:'Chính sách riêng tư'},'이용약관':{en:'Terms of Use',ja:'利用規約',tl:'Mga Tuntunin',vi:'Điều khoản sử dụng'},'고객지원':{en:'Support',ja:'サポート',tl:'Suporta',vi:'Hỗ trợ'}
};
function norm(s){return(s||'').replace(/\s+/g,' ').trim()}
function tr(s,lang){if(lang==='ko')return s;const n=norm(s);if(B[n]?.[lang])return B[n][lang];let out=s;Object.entries(B).sort((a,b)=>b[0].length-a[0].length).forEach(([k,v])=>{if(v[lang]&&out.includes(k))out=out.split(k).join(v[lang])});if(lang==='en'||lang==='tl'||lang==='vi')out=out.replace(/(\d{4})년/g,'$1').replace(/(\d{2})월/g,lang==='vi'?'Tháng $1':lang==='tl'?'Buwan $1':'Month $1').replace(/(\d{2})일/g,lang==='vi'?'Ngày $1':lang==='tl'?'Araw $1':'Day $1');return out}
function translateDom(lang){document.documentElement.lang=lang;document.querySelectorAll('body *').forEach(el=>{if(['SCRIPT','STYLE','NOSCRIPT'].includes(el.tagName)||el.closest('.language-switcher'))return;if(el.tagName==='INPUT'&&el.placeholder){el.dataset.koPlaceholder??=el.placeholder;el.placeholder=lang==='ko'?el.dataset.koPlaceholder:tr(el.dataset.koPlaceholder,lang)}if(el.tagName==='OPTION'){el.dataset.koText??=el.textContent;el.textContent=lang==='ko'?el.dataset.koText:tr(el.dataset.koText,lang);return}[...el.childNodes].filter(n=>n.nodeType===3&&norm(n.nodeValue)).forEach(n=>{n.__ko??=n.nodeValue;n.nodeValue=lang==='ko'?n.__ko:tr(n.__ko,lang)})});document.querySelectorAll('.lang-choice').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang))}
function setLang(lang,remember=true){if(!ORDER.includes(lang))lang='en';if(remember)localStorage.setItem('lumen-lang',lang);window.LUMEN_LANG=lang;translateDom(lang);setTimeout(()=>translateDom(lang),180);setTimeout(()=>translateDom(lang),650)}
function buildBar(){if(document.querySelector('.language-switcher'))return;const bar=document.createElement('div');bar.className='language-switcher';ORDER.forEach(code=>{const b=document.createElement('button');b.type='button';b.className='lang-choice';b.dataset.lang=code;b.title=LANGS[code][1];b.setAttribute('aria-label',LANGS[code][1]);b.textContent=LANGS[code][0];b.onclick=()=>setLang(code,true);bar.appendChild(b)});const h=document.querySelector('.fortune-header')||document.querySelector('.site-header');h?h.insertAdjacentElement('afterend',bar):document.body.prepend(bar)}
async function detect(){const saved=localStorage.getItem('lumen-lang');if(saved&&ORDER.includes(saved))return saved;try{const t=await(await fetch('/cdn-cgi/trace',{cache:'no-store'})).text(),loc=(t.match(/(?:^|\n)loc=([^\n]+)/)||[])[1];if(COUNTRY[loc])return COUNTRY[loc]}catch{}const n=(navigator.language||'en').toLowerCase();if(n.startsWith('ko'))return'ko';if(n.startsWith('ja'))return'ja';if(n.startsWith('tl')||n.startsWith('fil'))return'tl';if(n.startsWith('vi'))return'vi';return'en'}
async function init(){buildBar();const lang=await detect();setLang(lang,false);let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>translateDom(window.LUMEN_LANG||lang),100)}).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.LUMEN_I18N={setLang,translateString:tr};
})();