(()=>{
const qs=new URLSearchParams(location.search);let lang=(qs.get('lang')||'ko').toLowerCase();if(lang.startsWith('ja'))lang='ja';else if(lang.startsWith('vi'))lang='vi';else if(lang.startsWith('tl')||lang.startsWith('fil'))lang='tl';else if(lang.startsWith('en'))lang='en';else lang='ko';
const STEMS='갑을병정무기경신임계'.split(''),BRANCHES='자축인묘진사오미신유술해'.split('');
const COMB=[['자','축'],['인','해'],['묘','술'],['진','유'],['사','신'],['오','미']],CLASH=[['자','오'],['축','미'],['인','신'],['묘','유'],['진','술'],['사','해']],HARM=[['자','미'],['축','오'],['인','사'],['묘','진'],['신','해'],['유','술']],BREAK=[['자','유'],['축','진'],['인','해'],['묘','오'],['사','신'],['미','술']];
const T={ko:{title:'세운 · 월운 · 일운 흐름',desc:'현재의 연·월·일 기운을 원국의 네 기둥과 비교해 변화 포인트를 정리합니다.',year:'올해',month:'이번 달',day:'오늘',good:'조화가 비교적 많은 흐름',change:'변화와 조정이 필요한 흐름',steady:'큰 충돌보다 기본 흐름을 활용하기 좋은 시기',comb:'합',clash:'충',harm:'해',break:'파',note:'운세는 확정된 사건이 아니라 시기별 관계를 읽는 참고 지표입니다.'},en:{title:'Year · Month · Day flow',desc:'Compares the current year, month and day branches with your natal Four Pillars.',year:'This year',month:'This month',day:'Today',good:'A relatively harmonious flow',change:'A period needing adjustment and flexibility',steady:'A steadier period with no major branch conflict',comb:'Combination',clash:'Clash',harm:'Harm',break:'Break',note:'These cycles are interpretive timing indicators, not guaranteed events.'},ja:{title:'年運・月運・日運の流れ',desc:'現在の年・月・日の地支を命式の四柱と比較して変化点を整理します。',year:'今年',month:'今月',day:'今日',good:'調和が比較的多い流れ',change:'変化と調整が必要な流れ',steady:'大きな衝突が少なく基本の流れを活かしやすい時期',comb:'合',clash:'冲',harm:'害',break:'破',note:'運勢は確定した出来事ではなく、時期の関係を見る参考指標です。'},tl:{title:'Year · Month · Day flow',desc:'Inihahambing ang kasalukuyang year, month at day branches sa natal Four Pillars.',year:'Ngayong taon',month:'Ngayong buwan',day:'Ngayon',good:'Mas harmonious na flow',change:'Panahong kailangan ng adjustment at flexibility',steady:'Mas steady na panahon na walang malaking branch conflict',comb:'Combination',clash:'Clash',harm:'Harm',break:'Break',note:'Timing indicator lamang ito at hindi garantisadong pangyayari.'},vi:{title:'Dòng Năm · Tháng · Ngày',desc:'So sánh Địa Chi của năm, tháng và ngày hiện tại với Tứ Trụ gốc.',year:'Năm nay',month:'Tháng này',day:'Hôm nay',good:'Dòng chảy tương đối hài hòa',change:'Giai đoạn cần điều chỉnh và linh hoạt',steady:'Giai đoạn ổn định hơn, ít xung đột lớn',comb:'Hợp',clash:'Xung',harm:'Hại',break:'Phá',note:'Đây là chỉ báo tham khảo về thời vận, không phải sự kiện chắc chắn.'}}[lang];
function pairHas(arr,a,b){return arr.some(x=>(x[0]===a&&x[1]===b)||(x[0]===b&&x[1]===a))}
function natalBranches(){return[...document.querySelectorAll('#pillarGrid .pillar-card')].map(c=>{const s=(c.querySelector('.pillar-value')||c.querySelector('strong'))?.textContent||'';return BRANCHES.find(b=>s.includes(b))}).filter(Boolean)}
function yearPillar(y){const si=(y-4)%10,bi=(y-4)%12;return STEMS[(si+10)%10]+BRANCHES[(bi+12)%12]}
function monthBranch(m){return BRANCHES[(m+1)%12]}
function dayBranch(d){const base=Date.UTC(2000,0,7),days=Math.floor((Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())-base)/86400000);return BRANCHES[((days%12)+12)%12]}
function analyze(branch,natal){let comb=0,clash=0,harm=0,brk=0;natal.forEach(b=>{if(pairHas(COMB,branch,b))comb++;if(pairHas(CLASH,branch,b))clash++;if(pairHas(HARM,branch,b))harm++;if(pairHas(BREAK,branch,b))brk++});const score=comb-(clash*2+harm+brk);const mood=score>0?T.good:(clash+harm+brk>0?T.change:T.steady);const tags=[];if(comb)tags.push(`${T.comb} ${comb}`);if(clash)tags.push(`${T.clash} ${clash}`);if(harm)tags.push(`${T.harm} ${harm}`);if(brk)tags.push(`${T.break} ${brk}`);return{mood,tags:tags.join(' · ')||'—'}}
function render(){const content=document.getElementById('manseContent'),target=document.getElementById('transitReading');if(!content||!target||content.hidden)return false;const natal=natalBranches();if(natal.length<3)return false;const now=new Date(),yp=yearPillar(now.getFullYear()),yb=yp[1],mb=monthBranch(now.getMonth()+1),db=dayBranch(now),rows=[[T.year,yp,yb],[T.month,mb,mb],[T.day,db,db]].map(([label,p,b])=>{const a=analyze(b,natal);return`<article><span>${label}</span><strong>${p}</strong><p>${a.mood}</p><small>${a.tags}</small></article>`}).join('');target.innerHTML=`<div class="panel-heading"><div><p class="section-label">LUMEN TRANSIT</p><h2>${T.title}</h2><p class="panel-copy">${T.desc}</p></div></div><div class="transit-grid">${rows}</div><p class="transit-note">※ ${T.note}</p>`;target.hidden=false;return true}
let n=0;const timer=setInterval(()=>{if(render()||++n>100)clearInterval(timer)},100);
})();