(()=>{
const qs=new URLSearchParams(location.search);let lang=(qs.get('lang')||'ko').toLowerCase();if(lang.startsWith('ja'))lang='ja';else if(lang.startsWith('vi'))lang='vi';else if(lang.startsWith('tl')||lang.startsWith('fil'))lang='tl';else if(lang.startsWith('en'))lang='en';else lang='ko';
const T={ko:{title:'재성 위치와 금전 흐름',desc:'정재·편재가 어느 기둥과 지장간에 나타나는지 확인하고, 현재 운의 재성과 겹치는지를 함께 봅니다.',direct:'정재',indirect:'편재',visible:'천간에 드러난 재성',hidden:'지장간 속 재성',current:'현재 운의 재성',none:'뚜렷한 재성이 표면에 강하게 드러나지 않습니다.',manage:'관리·축적형 흐름',opportunity:'기회·유동자원형 흐름',mixed:'관리와 기회형 흐름이 함께 보입니다.',note:'재성이 많다고 반드시 부유함을 뜻하지 않으며, 실제 재무 판단은 소득·부채·현금흐름과 함께 봐야 합니다.'},en:{title:'Wealth-star placement & money flow',desc:'Checks where Direct and Indirect Wealth appear in the visible stems and hidden stems, then compares them with the current cycle.',direct:'Direct Wealth',indirect:'Indirect Wealth',visible:'Visible wealth stars',hidden:'Hidden-stem wealth',current:'Current-cycle wealth',none:'No wealth star is strongly visible on the surface.',manage:'Management and accumulation pattern',opportunity:'Opportunity and flexible-resource pattern',mixed:'Both management and opportunity patterns appear.',note:'More wealth stars do not guarantee greater wealth; real financial decisions should use income, debt and cash-flow data.'},ja:{title:'財星の位置と金運の流れ',desc:'正財・偏財が天干と蔵干のどこに現れるかを確認し、現在運の財星との重なりも見ます。',direct:'正財',indirect:'偏財',visible:'天干に出る財星',hidden:'蔵干の財星',current:'現在運の財星',none:'表面に強い財星は目立ちません。',manage:'管理・蓄積型の流れ',opportunity:'機会・流動資源型の流れ',mixed:'管理型と機会型の両方が見られます。',note:'財星の多さは富を保証しません。実際の判断では収入・負債・キャッシュフローも確認してください。'},tl:{title:'Wealth-star placement at money flow',desc:'Tinitingnan kung saan lumalabas ang Direct at Indirect Wealth sa visible at hidden stems at kung paano ito tumutugma sa current cycle.',direct:'Direct Wealth',indirect:'Indirect Wealth',visible:'Visible wealth stars',hidden:'Hidden wealth stars',current:'Current-cycle wealth',none:'Walang malakas na wealth star na visible sa surface.',manage:'Management at accumulation pattern',opportunity:'Opportunity at flexible-resource pattern',mixed:'May halong management at opportunity pattern.',note:'Hindi garantiya ng yaman ang dami ng wealth stars; gamitin pa rin ang tunay na income, debt at cash-flow data.'},vi:{title:'Vị trí Tài Tinh và dòng tiền',desc:'Kiểm tra Chính Tài, Thiên Tài trong Thiên Can và Tàng Can, đồng thời so với vận hiện tại.',direct:'Chính Tài',indirect:'Thiên Tài',visible:'Tài Tinh lộ ở Thiên Can',hidden:'Tài Tinh trong Tàng Can',current:'Tài Tinh của vận hiện tại',none:'Không có Tài Tinh nổi bật mạnh ở bề mặt.',manage:'Xu hướng quản lý và tích lũy',opportunity:'Xu hướng cơ hội và nguồn lực linh hoạt',mixed:'Có cả xu hướng quản lý lẫn cơ hội.',note:'Nhiều Tài Tinh không đảm bảo giàu có; quyết định tài chính thực tế vẫn cần dựa vào thu nhập, nợ và dòng tiền.'}}[lang];
const DIRECT_WORDS={ko:['정재'],en:['Direct Wealth'],ja:['正財'],tl:['Direct Wealth'],vi:['Chính Tài']},INDIRECT_WORDS={ko:['편재'],en:['Indirect Wealth'],ja:['偏財'],tl:['Indirect Wealth'],vi:['Thiên Tài']};
function txt(el){return(el?.textContent||'').replace(/\s+/g,' ').trim()}
function countWords(text,words){return words.reduce((n,w)=>n+(text.split(w).length-1),0)}
function classify(d,i){if(d&&i)return T.mixed;if(d)return T.manage;if(i)return T.opportunity;return T.none}
function render(){const content=document.getElementById('manseContent'),panel=document.getElementById('wealthDetail');if(!content||!panel||content.hidden)return false;const visibleText=[...document.querySelectorAll('#tenGodGrid strong')].map(txt).join(' '),hiddenText=[...document.querySelectorAll('#hiddenStemGrid small')].map(txt).join(' '),currentText=[txt(document.getElementById('yearText')),txt(document.getElementById('monthText')),txt(document.getElementById('todayText'))].join(' ');const dw=DIRECT_WORDS[lang],iw=INDIRECT_WORDS[lang];const vd=countWords(visibleText,dw),vi=countWords(visibleText,iw),hd=countWords(hiddenText,dw),hi=countWords(hiddenText,iw),cd=countWords(currentText,dw),ci=countWords(currentText,iw);const totalD=vd+hd,totalI=vi+hi;panel.innerHTML=`<div class="panel-heading"><div><p class="section-label">LUMEN WEALTH MAP</p><h2>${T.title}</h2><p class="panel-copy">${T.desc}</p></div></div><div class="wealth-map-grid"><article><span>${T.visible}</span><strong>${T.direct} ${vd} · ${T.indirect} ${vi}</strong><p>${classify(vd,vi)}</p></article><article><span>${T.hidden}</span><strong>${T.direct} ${hd} · ${T.indirect} ${hi}</strong><p>${classify(hd,hi)}</p></article><article><span>${T.current}</span><strong>${T.direct} ${cd} · ${T.indirect} ${ci}</strong><p>${classify(cd,ci)}</p></article><article><span>${T.title}</span><strong>${T.direct} ${totalD} · ${T.indirect} ${totalI}</strong><p>${classify(totalD,totalI)}</p></article></div><p class="transit-note">※ ${T.note}</p>`;panel.hidden=false;return true}
let n=0;const timer=setInterval(()=>{if(render()||++n>100)clearInterval(timer)},100);
})();