const base=(process.env.LUMEN_PROD_BASE_URL||'https://lumendestiny.com').replace(/\/$/,'');
const langs=['ko','en','ja','tl','vi','zh'];
const corePaths=['/','/compatibility','/guardian','/guardian-order','/guardian-verify'];
const pages=[];
for(const lang of langs){for(const p of corePaths)pages.push(`${p}?lang=${lang}`)}
pages.push('/privacy.html','/terms.html','/refund-policy.html','/support.html','/guardian-gift?lang=ko','/guardian-campaigns?lang=ko','/guardian-gallery?lang=ko','/guardian-physical-status?lang=ko');
const timeoutMs=12000;
async function fetchOnce(url,options={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeoutMs);try{return await fetch(url,{redirect:'manual',...options,signal:c.signal})}finally{clearTimeout(t)}}
async function fetchChecked(path){let url=base+path;const seen=new Set(),chain=[];for(let i=0;i<12;i++){if(seen.has(url))throw new Error(`${path}: redirect loop ${chain.join(' -> ')} -> ${url}`);seen.add(url);const r=await fetchOnce(url);chain.push(`${r.status} ${url}`);if(r.status>=300&&r.status<400){const loc=r.headers.get('location');if(!loc)throw new Error(`${path}: ${r.status} without Location; ${chain.join(' -> ')}`);url=new URL(loc,url).toString();continue}const text=await r.text();if(!r.ok)throw new Error(`${path}: HTTP ${r.status}; ${chain.join(' -> ')}`);if(/ERR_TOO_MANY_REDIRECTS|too many redirects/i.test(text))throw new Error(`${path}: redirect-loop error page; ${chain.join(' -> ')}`);console.log(`CHAIN ${path}: ${chain.join(' -> ')}`);return{r,text,url}}throw new Error(`${path}: too many redirect hops; ${chain.join(' -> ')}`)}
async function check404(){const path='/__lumen-v1-missing-route__?lang=zh';const r=await fetchOnce(base+path);const text=await r.text();if(r.status!==404)throw new Error(`${path}: expected HTTP 404, got ${r.status}`);if(!/404|找不到页面|Page not found/i.test(text))throw new Error(`${path}: custom recovery page content missing`);console.log(`404 ${path}: ${r.status} custom recovery page OK`)}
let lastErr;for(let attempt=1;attempt<=4;attempt++){try{for(const p of pages)await fetchChecked(p);await check404();const h=await fetchChecked('/api/health');let data;try{data=JSON.parse(h.text)}catch{throw new Error('/api/health: invalid JSON')}if(data?.ok!==true)throw new Error('/api/health: ok=true missing');console.log('HEALTH',JSON.stringify({version:data.version,features:data.features,configured:data.configured}));console.log(`Production smoke test passed for ${langs.length} languages and ${pages.length} public routes.`);process.exit(0)}catch(e){lastErr=e;console.error(`Attempt ${attempt}/4 failed:`,e?.message||e);if(attempt<4)await new Promise(r=>setTimeout(r,10000))}}console.error('Production smoke test failed:',lastErr?.message||lastErr);process.exit(1);
