import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { calculateCompatibility, CompatibilityResult } from '../lib/compatibility-engine';
import type { SajuInput } from '../lib/saju-session';

type Person={name:string;birthDate:string;birthTime:string;calendar:'solar'|'lunar'};
const empty=():Person=>({name:'',birthDate:'',birthTime:'',calendar:'solar'});

export default function CompatibilityScreen(){
 const [a,setA]=useState<Person>(empty()),[b,setB]=useState<Person>(empty()),[result,setResult]=useState<CompatibilityResult|null>(null),[message,setMessage]=useState('');
 const valid=(p:Person)=>!!p.name.trim()&&/^\d{4}-\d{2}-\d{2}$/.test(p.birthDate.trim())&&(!p.birthTime.trim()||/^\d{2}:\d{2}$/.test(p.birthTime.trim()));
 const run=()=>{setMessage('');setResult(null);if(!valid(a)||!valid(b)){setMessage('두 사람의 이름과 생년월일(YYYY-MM-DD)을 확인해 주세요. 출생시간은 알면 HH:MM 형식으로 입력해 주세요.');return}try{const toInput=(p:Person):SajuInput=>({name:p.name.trim(),birthDate:p.birthDate.trim(),birthTime:p.birthTime.trim(),calendar:p.calendar,gender:'unspecified'});setResult(calculateCompatibility(toInput(a),toInput(b)))}catch{setMessage('궁합 계산에 실패했습니다. 날짜와 시간을 다시 확인해 주세요.')}};
 return <ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled">
  <Text style={s.label}>LUMEN COMPATIBILITY · APP V1</Text><Text style={s.title}>두 사람의 궁합</Text><Text style={s.lead}>두 명식을 앱 안에서 계산해 일간 관계와 지지 합·충·해를 비교하고, 실제 관계에서 도움이 되는 방향으로 풀어드립니다.</Text>
  <PersonCard title="첫 번째 사람" value={a} onChange={setA}/><PersonCard title="두 번째 사람" value={b} onChange={setB}/>
  <Pressable style={s.primary} onPress={run}><Text style={s.primaryText}>무료 궁합 결과 보기</Text></Pressable>{message?<Text style={s.message}>{message}</Text>:null}
  {result?<View style={s.result}><Text style={s.score}>{result.score}점</Text><Text style={s.headline}>{result.headline}</Text><Text style={s.copy}>{result.dayMasterText}</Text><Text style={s.copy}>{result.branchText}</Text><Block title="잘 맞는 흐름" items={result.strengths}/><Block title="조심하면 좋은 흐름" items={result.cautions}/><Block title="관계를 위한 실천" items={result.practical}/><View style={s.elements}><Text style={s.blockTitle}>두 사람의 표면 오행</Text><Text style={s.copy}>{result.a.name} · {Object.entries(result.a.elements).map(([k,v])=>`${k} ${v}`).join(' · ')}</Text><Text style={s.copy}>{result.b.name} · {Object.entries(result.b.elements).map(([k,v])=>`${k} ${v}`).join(' · ')}</Text></View><Text style={s.disclaimer}>※ 궁합 점수와 해설은 전통 명리 요소를 이해하기 쉽게 구조화한 참고 콘텐츠입니다. 관계의 성패를 확정하거나 중요한 결정을 대신하지 않습니다.</Text></View>:null}
  <Text style={s.privacy}>입력한 두 사람의 정보는 이 화면에서 계산에만 사용하며 계정이나 Guardian 보관함에 저장하지 않습니다.</Text>
 </ScrollView>
}
function PersonCard({title,value,onChange}:{title:string;value:Person;onChange:(v:Person)=>void}){return <View style={s.card}><Text style={s.cardTitle}>{title}</Text><TextInput style={s.input} value={value.name} onChangeText={x=>onChange({...value,name:x})} placeholder="이름 또는 닉네임"/><TextInput style={s.input} value={value.birthDate} onChangeText={x=>onChange({...value,birthDate:x})} placeholder="생년월일 YYYY-MM-DD" keyboardType="numbers-and-punctuation"/><TextInput style={s.input} value={value.birthTime} onChangeText={x=>onChange({...value,birthTime:x})} placeholder="출생시간 HH:MM · 모르면 비워두기" keyboardType="numbers-and-punctuation"/><View style={s.toggleRow}>{(['solar','lunar'] as const).map(v=><Pressable key={v} onPress={()=>onChange({...value,calendar:v})} style={[s.toggle,value.calendar===v&&s.toggleOn]}><Text style={[s.toggleText,value.calendar===v&&s.toggleTextOn]}>{v==='solar'?'양력':'음력'}</Text></Pressable>)}</View></View>}
function Block({title,items}:{title:string;items:string[]}){return <View style={s.block}><Text style={s.blockTitle}>{title}</Text>{items.map((x,i)=><Text key={i} style={s.item}>• {x}</Text>)}</View>}
const s=StyleSheet.create({page:{padding:18,paddingBottom:52,backgroundColor:'#fff',flexGrow:1},label:{fontSize:12,fontWeight:'900',letterSpacing:1.5,color:'#6b5bd2'},title:{fontSize:30,fontWeight:'900',color:'#242637',marginTop:7},lead:{fontSize:14,lineHeight:22,color:'#676d7a',marginTop:8},card:{marginTop:16,padding:16,borderWidth:1,borderColor:'#e2e4ea',borderRadius:17,backgroundColor:'#fbfbfe'},cardTitle:{fontSize:16,fontWeight:'900',color:'#343746',marginBottom:8},input:{marginTop:8,borderWidth:1,borderColor:'#dfe1e8',borderRadius:12,paddingHorizontal:12,paddingVertical:12,fontSize:14,backgroundColor:'#fff'},toggleRow:{flexDirection:'row',gap:8,marginTop:10},toggle:{flex:1,minHeight:40,borderWidth:1,borderColor:'#dadce5',borderRadius:10,alignItems:'center',justifyContent:'center'},toggleOn:{backgroundColor:'#4f3ad6',borderColor:'#4f3ad6'},toggleText:{fontSize:13,fontWeight:'800',color:'#5d6370'},toggleTextOn:{color:'#fff'},primary:{marginTop:18,minHeight:49,borderRadius:13,backgroundColor:'#4f3ad6',alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontSize:14,fontWeight:'900'},message:{fontSize:13,lineHeight:20,color:'#9a4747',marginTop:10},result:{marginTop:22,padding:18,borderRadius:19,borderWidth:1,borderColor:'#dddfe7',backgroundColor:'#fbfbfe'},score:{fontSize:40,fontWeight:'900',color:'#4f3ad6'},headline:{fontSize:21,fontWeight:'900',color:'#2e3040',marginTop:4},copy:{fontSize:13,lineHeight:21,color:'#5d6370',marginTop:7},block:{marginTop:18},blockTitle:{fontSize:15,fontWeight:'900',color:'#383b49',marginBottom:6},item:{fontSize:13,lineHeight:21,color:'#555b68',marginTop:4},elements:{marginTop:18,padding:14,borderRadius:14,backgroundColor:'#f7f5ff'},disclaimer:{fontSize:12,lineHeight:19,color:'#777d89',marginTop:18},privacy:{fontSize:12,lineHeight:19,color:'#777d89',marginTop:18}});
