import { useEffect, useState } from 'react';
import { Pressable, ScrollView, Share, StyleSheet, Text, View } from 'react-native';
import QRCode from 'react-native-qrcode-svg';
import { addConnectionMember } from '../lib/connection-vault';
import type { NetworkMember } from '../lib/connection-network';
import { buildLumenLinkUrl, getLumenLinkInviteStatus } from '../lib/lumen-link-api';
import { loadPendingInvites, PendingInvite, pruneExpiredInvites, removePendingInvite } from '../lib/lumen-link-invite-vault';

export default function LinkInvitesScreen(){
 const [items,setItems]=useState<PendingInvite[]>([]),[busy,setBusy]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{pruneExpiredInvites().then(setItems)},[]);
 const share=async(item:PendingInvite)=>{const url=buildLumenLinkUrl(item.token);await Share.share({title:'LUMEN LINK 인연 오행지도',message:`LUMEN LINK 인연 오행지도 초대입니다.\n${url}`,url});};
 const check=async(item:PendingInvite)=>{setBusy(item.id);setMessage('');try{const s=await getLumenLinkInviteStatus(item.token);if(!s.relationship){setMessage('아직 상대방이 참여하지 않았습니다.');return}const r=s.relationship;const member:NetworkMember={id:r.id,name:r.participantLabel,relation:r.relationLabel||'링크 참여',elements:r.elements as NetworkMember['elements'],score:r.score,grade:r.grade as NetworkMember['grade'],addedAt:r.createdAt};await addConnectionMember(member);setItems(await removePendingInvite(item.id));setMessage(`${r.participantLabel}님의 참여 결과를 인연지도에 반영했습니다.`)}catch{setMessage('초대 상태를 확인하지 못했습니다.')}finally{setBusy('')}};
 const remove=async(id:string)=>setItems(await removePendingInvite(id));
 return <ScrollView contentContainerStyle={s.page}><Text style={s.label}>LUMEN LINK</Text><Text style={s.title}>보낸 초대 관리</Text><Text style={s.lead}>앱을 닫아도 아직 사용되지 않은 초대 링크를 다시 확인할 수 있습니다.</Text>{message?<Text style={s.message}>{message}</Text>:null}{items.length?items.map(item=>{const url=buildLumenLinkUrl(item.token);return <View key={item.id} style={s.card}><Text style={s.name}>{item.label||'인연지도 초대'}</Text><Text style={s.meta}>만료 {new Date(item.expiresAt).toLocaleString()}</Text><View style={s.qr}><QRCode value={url} size={142}/></View><Text selectable style={s.url}>{url}</Text><Pressable style={s.primary} onPress={()=>share(item)}><Text style={s.primaryText}>다시 공유하기</Text></Pressable><Pressable style={s.secondary} disabled={busy===item.id} onPress={()=>check(item)}><Text style={s.secondaryText}>{busy===item.id?'확인 중…':'참여 결과 확인'}</Text></Pressable><Pressable onPress={()=>remove(item.id)}><Text style={s.delete}>초대 기록 삭제</Text></Pressable></View>}):<View style={s.empty}><Text style={s.emptyTitle}>대기 중인 초대가 없습니다.</Text><Text style={s.meta}>인연 오행지도에서 초대 링크를 만들면 이곳에서 다시 확인할 수 있습니다.</Text></View>}<Text style={s.privacy}>초대 기록에는 토큰·만료시각 등 연결에 필요한 정보만 기기에 저장합니다. 상대방의 생년월일·출생시간 원본은 저장하지 않습니다.</Text></ScrollView>
}
const s=StyleSheet.create({page:{padding:20,paddingBottom:48,backgroundColor:'#fff',flexGrow:1},label:{marginTop:16,fontSize:12,fontWeight:'900',letterSpacing:2.2,color:'#5146c8'},title:{marginTop:8,fontSize:32,fontWeight:'900'},lead:{marginTop:10,fontSize:15,lineHeight:24,color:'#626875'},message:{marginTop:16,padding:12,borderRadius:12,backgroundColor:'#f3f1ff',fontSize:13,lineHeight:20,color:'#5146c8'},card:{marginTop:18,padding:18,borderWidth:1,borderColor:'#e5e6ec',borderRadius:20,backgroundColor:'#fbfbfe'},name:{fontSize:18,fontWeight:'900'},meta:{marginTop:6,fontSize:12,lineHeight:19,color:'#737986'},qr:{marginTop:16,alignItems:'center'},url:{marginTop:12,fontSize:11,lineHeight:17,color:'#777d89'},primary:{marginTop:16,minHeight:46,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:'#1f2330'},primaryText:{color:'#fff',fontWeight:'900'},secondary:{marginTop:10,minHeight:44,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:'#ece9ff'},secondaryText:{color:'#5146c8',fontWeight:'900'},delete:{marginTop:14,textAlign:'center',fontSize:12,fontWeight:'800',color:'#9a4747'},empty:{marginTop:22,padding:20,borderRadius:18,backgroundColor:'#f7f7fa'},emptyTitle:{fontSize:17,fontWeight:'900'},privacy:{marginTop:20,fontSize:12,lineHeight:19,color:'#777d89'}});
