import { useEffect, useState } from 'react';
import { useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { calculateNativeSaju } from '../lib/saju-engine';
import type { SajuInput } from '../lib/saju-session';
import { getLumenLinkInvite, joinLumenLinkInvite, PublicLinkInvite } from '../lib/lumen-link-api';

type Person={name:string;birthDate:string;birthTime:string;calendar:'solar'|'lunar';relation:string};

export default function LinkJoinScreen(){
 const params=useLocalSearchParams<{token?:string}>();
 const token=typeof params.token==='string'?params.token:'';
 const [invite,setInvite]=useState<PublicLinkInvite|null>(null);
 const [person,setPerson]=useState<Person>({name:'',birthDate:'',birthTime:'',calendar:'solar',relation:'친구'});
 const [message,setMessage]=useState('초대 정보를 확인하는 중입니다.');
 const [busy,setBusy]=useState(false);
 const [done,setDone]=useState<{score:number;grade:string;strongestForInviter:string|null;strongestForParticipant:string|null}|null>(null);
 useEffect(()=>{if(!token){setMessage('유효한 초대 토큰이 없습니다.');return;}getLumenLinkInvite(token).then(x=>{setInvite(x);setMessage(x.status==='open'?'':'이 초대는 이미 사용됐거나 만료되었습니다.')}).catch(()=>setMessage('초대 정보를 불러오지 못했습니다.'))},[token]);
 const valid=()=>!!person.name.trim()&&/^\d{4}-\d{2}-\d{2}$/.test(person.birthDate.trim())&&(!person.birthTime.trim()||/^\d{2}:\d{2}$/.test(person.birthTime.trim()));
 const join=async()=>{if(!invite||invite.status!=='open')return;if(!valid()){setMessage('이름과 생년월일(YYYY-MM-DD)을 확인해 주세요. 출생시간은 알면 HH:MM으로 입력해 주세요.');return;}setBusy(true);setMessage('');try{const input:SajuInput={name:person.name.trim(),birthDate:person.birthDate.trim(),birthTime:person.birthTime.trim(),calendar:person.calendar,gender:'unspecified'};const saju=calculateNativeSaju(input);const r=await joinLumenLinkInvite({token,participantLabel:person.name.trim(),relationLabel:person.relation.trim()||'지인',elements:saju.elements,weakest:saju.weakest});setDone(r);setMessage('참여가 완료되었습니다. 입력한 생년월일과 출생시간 원본은 초대한 사람에게 전달되지 않습니다.')}catch(e){const code=e instanceof Error?e.message:'';setMessage(code==='invite_closed'?'이미 사용된 초대입니다.':code==='invite_expired'?'만료된 초대입니다.':'참여 처리에 실패했습니다. 잠시 후 다시 시도해 주세요.')}finally{setBusy(false)}};
 return <ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled">
  <Text style={s.eyebrow}>LUMEN LINK</Text><Text style={s.title}>인연 오행지도 초대</Text>
  <Text style={s.lead}>{invite?`${invite.inviterLabel}님이 인연 오행지도에 초대했습니다.`:'초대 링크를 확인하고 있습니다.'}</Text>
  <View style={s.notice}><Text style={s.noticeTitle}>내 정보는 내가 직접 입력합니다</Text><Text style={s.noticeCopy}>생년월일과 출생시간은 이 기기에서 명식 계산에 사용되며, 서버에는 계산된 오행 분포와 관계 결과만 전달합니다. 원본 출생정보는 초대한 사람에게 공개되지 않습니다.</Text></View>
  {!done&&invite?.status==='open'?<View style={s.card}><Text style={s.cardTitle}>내 정보</Text><TextInput style={s.input} value={person.relation} onChangeText={x=>setPerson({...person,relation:x})} placeholder="상대와의 관계 · 예: 친구, 가족, 동료"/><TextInput style={s.input} value={person.name} onChangeText={x=>setPerson({...person,name:x})} placeholder="이름 또는 닉네임"/><TextInput style={s.input} value={person.birthDate} onChangeText={x=>setPerson({...person,birthDate:x})} placeholder="생년월일 YYYY-MM-DD" keyboardType="numbers-and-punctuation"/><TextInput style={s.input} value={person.birthTime} onChangeText={x=>setPerson({...person,birthTime:x})} placeholder="출생시간 HH:MM · 모르면 비워두기" keyboardType="numbers-and-punctuation"/><View style={s.toggleRow}>{(['solar','lunar'] as const).map(v=><Pressable key={v} onPress={()=>setPerson({...person,calendar:v})} style={[s.toggle,person.calendar===v&&s.toggleOn]}><Text style={[s.toggleText,person.calendar===v&&s.toggleTextOn]}>{v==='solar'?'양력':'음력'}</Text></Pressable>)}</View><Pressable style={s.primary} onPress={join} disabled={busy}><Text style={s.primaryText}>{busy?'계산 중…':'동의하고 인연지도 참여하기'}</Text></Pressable></View>:null}
  {done?<View style={s.result}><Text style={s.score}>{done.score}</Text><Text style={s.grade}>{done.grade}</Text><Text style={s.copy}>오행 보완도는 관계의 좋고 나쁨을 판정하는 점수가 아니라 두 명식의 부족·초과 오행이 서로 얼마나 보완되는지 나타내는 참고값입니다.</Text>{done.strongestForInviter?<Text style={s.point}>내가 상대에게 보완하는 기운 · {done.strongestForInviter}</Text>:null}{done.strongestForParticipant?<Text style={s.point}>상대가 나에게 보완하는 기운 · {done.strongestForParticipant}</Text>:null}</View>:null}
  {message?<Text style={s.message}>{message}</Text>:null}<Text style={s.privacy}>※ 입력 정보는 명리 참고 콘텐츠 제공을 위한 계산에만 사용합니다. 중요한 관계 판단을 대신하지 않습니다.</Text>
 </ScrollView>
}
const s=StyleSheet.create({page:{padding:20,paddingBottom:48,backgroundColor:'#fff',flexGrow:1},eyebrow:{marginTop:20,fontSize:12,letterSpacing:2.4,fontWeight:'900',color:'#5146c8'},title:{marginTop:8,fontSize:31,lineHeight:39,fontWeight:'900'},lead:{marginTop:10,fontSize:16,lineHeight:25,color:'#555b68'},notice:{marginTop:20,padding:17,borderRadius:18,backgroundColor:'#f3f1ff'},noticeTitle:{fontSize:16,fontWeight:'900',color:'#5146c8'},noticeCopy:{marginTop:8,fontSize:13,lineHeight:21,color:'#5d6370'},card:{marginTop:18,padding:18,borderWidth:1,borderColor:'#e2e4ea',borderRadius:18},cardTitle:{fontSize:19,fontWeight:'900'},input:{marginTop:10,borderWidth:1,borderColor:'#dfe1e8',borderRadius:12,paddingHorizontal:12,paddingVertical:12,fontSize:14},toggleRow:{flexDirection:'row',gap:8,marginTop:10},toggle:{flex:1,minHeight:40,borderWidth:1,borderColor:'#dadce5',borderRadius:10,alignItems:'center',justifyContent:'center'},toggleOn:{backgroundColor:'#5146c8',borderColor:'#5146c8'},toggleText:{fontSize:13,fontWeight:'800',color:'#5d6370'},toggleTextOn:{color:'#fff'},primary:{marginTop:18,minHeight:50,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:'#1f2330'},primaryText:{color:'#fff',fontWeight:'900'},result:{marginTop:20,padding:20,borderRadius:20,backgroundColor:'#f7f6ff'},score:{fontSize:48,fontWeight:'900',color:'#5146c8'},grade:{fontSize:21,fontWeight:'900',marginTop:2},copy:{fontSize:13,lineHeight:21,color:'#5d6370',marginTop:10},point:{fontSize:14,lineHeight:22,fontWeight:'800',marginTop:10},message:{marginTop:16,fontSize:13,lineHeight:21,color:'#4f5663'},privacy:{marginTop:20,fontSize:12,lineHeight:19,color:'#777d89'}});
