import { useCallback, useState } from 'react';
import { Image, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useFocusEffect, router } from 'expo-router';
import { verifyGuardian, GuardianVerifyResponse } from '../lib/guardian-api';
import { GUARDIAN_PRODUCTS, TIER_LABEL } from '../lib/guardian-products';
import { removeVaultGuardian, saveVaultGuardian, VaultGuardian } from '../lib/guardian-vault';
import { syncGuardianVault } from '../lib/guardian-sync';

type Row={local:VaultGuardian;remote:GuardianVerifyResponse|null;loading:boolean};
const statusText:Record<string,string>={pending:'발급 대기',verified:'정상 발급',refund_pending:'환불 처리 대기',refunded:'환불 완료',format_only:'서버 점검 중',not_found:'기록 없음'};
const sourceText:Record<string,string>={issued:'내 발급',gift:'선물/Claim',manual:'이 기기에서만 보관'};

export default function MyGuardianScreen(){
 const [rows,setRows]=useState<Row[]>([]),[refreshing,setRefreshing]=useState(false),[id,setId]=useState(''),[message,setMessage]=useState(''),[signedIn,setSignedIn]=useState(false);
 const load=useCallback(async()=>{setRefreshing(true);const sync=await syncGuardianVault();setSignedIn(sync.signedIn);const local=sync.local;setRows(local.map(x=>({local:x,remote:null,loading:true})));const next=await Promise.all(local.map(async x=>{try{return{local:x,remote:await verifyGuardian(x.id),loading:false}}catch{return{local:x,remote:null,loading:false}}}));setRows(next);setRefreshing(false)},[]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 const add=async()=>{const clean=id.trim().toUpperCase();if(!/^LG-\d{8}-[A-Z0-9]{5,12}$/.test(clean)){setMessage('발급번호 형식을 확인해 주세요.');return}try{const r=await verifyGuardian(clean);if(!r.ok&&r.status==='not_found'){setMessage('서버에서 해당 발급번호를 찾지 못했습니다.');return}await saveVaultGuardian(clean,'manual');setId('');setMessage('이 기기 보관함에 추가했습니다. 이 등록만으로 계정 소유권이 생기지는 않습니다.');await load()}catch{setMessage('인증 서버 연결을 확인해 주세요.')}};
 const remove=async(v:string)=>{await removeVaultGuardian(v);await load()};
 return <ScrollView contentContainerStyle={s.page} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={load}/> } keyboardShouldPersistTaps="handled">
  <Text style={s.label}>MY LUMEN GUARDIAN</Text><Text style={s.title}>내 Guardian</Text><Text style={s.lead}>{signedIn?'로그인된 계정의 소유 Guardian과 이 기기 보관함을 함께 보여줍니다. 서버 소유권이 확인된 Guardian은 기기 변경 후에도 복원할 수 있습니다.':'내가 발급받았거나 선물 받은 Guardian의 발급번호를 이 기기에 보관하고, 서버 인증 상태를 언제든 다시 확인합니다.'}</Text>
  <View style={s.sync}><Text style={s.syncTitle}>{signedIn?'계정 동기화 연결됨':'로컬 보관 모드'}</Text><Text style={s.syncText}>{signedIn?'서버 소유 Guardian을 자동으로 불러와 발급번호 기준으로 합칩니다.':'로그인 전에는 이 기기에만 목록을 저장합니다. 수동 등록은 진품 조회용이며 소유권 Claim이 아닙니다.'}</Text></View>
  <View style={s.addBox}><Text style={s.addTitle}>Guardian 추가</Text><TextInput value={id} onChangeText={setId} autoCapitalize="characters" placeholder="LG-YYYYMMDD-XXXXXXXXXX" style={s.input}/><Pressable onPress={add} style={s.primary}><Text style={s.primaryText}>발급번호로 추가</Text></Pressable>{message?<Text style={s.message}>{message}</Text>:null}</View>
  {rows.length===0&&!refreshing?<View style={s.empty}><Text style={s.emptyTitle}>아직 보관된 Guardian이 없습니다.</Text><Text style={s.emptyText}>Guardian을 발급받거나 선물 받으면 발급번호를 추가해 한곳에서 관리할 수 있습니다.</Text><Pressable style={s.outline} onPress={()=>router.push('/guardian')}><Text style={s.outlineText}>Guardian 아카이브 보기</Text></Pressable></View>:null}
  {rows.map(({local,remote,loading})=>{const g=remote?.guardian,product=g?.guardianDesignKey?GUARDIAN_PRODUCTS.find(x=>x.key===g.guardianDesignKey):null;return <View key={local.id} style={s.card}>{product?<Image source={{uri:product.image}} style={s.image}/>:<View style={s.placeholder}/>}<View style={s.body}><Text style={s.source}>{sourceText[local.source]||local.source}</Text><Text style={s.status}>{loading?'인증 확인 중…':statusText[remote?.status||'']||'상태 미확인'}</Text><Text style={s.name}>{g?.displayName||product?.name||'Lumen Guardian'}</Text><Text style={s.line}>{local.id}</Text>{g?<><Text style={s.line}>{TIER_LABEL[g.tier as keyof typeof TIER_LABEL]||g.tier} · ${g.priceUsd}</Text><Text style={s.line}>고유번호 · {g.serial?`${g.serial}/${g.editionLimit}`:`발급 대기 / ${g.editionLimit}`}</Text>{g.issuedAt?<Text style={s.line}>발행일 · {new Date(g.issuedAt).toLocaleDateString()}</Text>:null}</>:null}<View style={s.actions}><Pressable style={s.smallPrimary} onPress={()=>router.push({pathname:'/guardian-verify',params:{id:local.id}})}><Text style={s.smallPrimaryText}>QR·인증 보기</Text></Pressable><Pressable style={s.remove} onPress={()=>remove(local.id)}><Text style={s.removeText}>이 기기 목록에서 삭제</Text></Pressable></View></View></View>})}
  <Text style={s.privacy}>수동으로 입력한 발급번호는 이 기기에만 저장되며 계정 소유권을 주장하지 않습니다. 계정 동기화가 활성화된 경우에도 서버에서 확인된 소유권만 자동 복원합니다. 소망 문구·생년월일·선물 메시지는 보관함 동기화 대상이 아닙니다.</Text>
 </ScrollView>
}
const s=StyleSheet.create({page:{padding:18,paddingBottom:52,backgroundColor:'#fff',flexGrow:1},label:{fontSize:12,fontWeight:'900',letterSpacing:1.5,color:'#6b5bd2'},title:{fontSize:30,fontWeight:'900',color:'#242637',marginTop:7},lead:{fontSize:14,lineHeight:22,color:'#676d7a',marginTop:8},sync:{marginTop:15,padding:14,borderRadius:14,backgroundColor:'#f7f5ff'},syncTitle:{fontSize:13,fontWeight:'900',color:'#4031a8'},syncText:{fontSize:12,lineHeight:19,color:'#676d7a',marginTop:4},addBox:{marginTop:18,padding:16,borderRadius:17,backgroundColor:'#f7f5ff'},addTitle:{fontSize:15,fontWeight:'900',color:'#4031a8',marginBottom:9},input:{borderWidth:1,borderColor:'#dedfe8',backgroundColor:'#fff',borderRadius:12,paddingHorizontal:12,paddingVertical:12,fontSize:14},primary:{marginTop:9,minHeight:44,borderRadius:12,backgroundColor:'#4f3ad6',alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontWeight:'900'},message:{fontSize:12,lineHeight:19,color:'#5c6270',marginTop:8},empty:{marginTop:22,padding:20,borderWidth:1,borderColor:'#e2e4ea',borderRadius:18,alignItems:'center'},emptyTitle:{fontSize:17,fontWeight:'900',color:'#303342'},emptyText:{fontSize:13,lineHeight:21,textAlign:'center',color:'#6c7280',marginTop:7},outline:{marginTop:13,paddingHorizontal:15,paddingVertical:11,borderRadius:11,borderWidth:1,borderColor:'#6b5bd2'},outlineText:{fontSize:13,fontWeight:'900',color:'#4f3ad6'},card:{marginTop:16,flexDirection:'row',gap:12,padding:12,borderWidth:1,borderColor:'#e1e3e9',borderRadius:17,backgroundColor:'#fbfbfe'},image:{width:104,aspectRatio:941/1672,borderRadius:11,backgroundColor:'#111'},placeholder:{width:104,aspectRatio:941/1672,borderRadius:11,backgroundColor:'#ececf2'},body:{flex:1,justifyContent:'center'},source:{fontSize:10,fontWeight:'900',color:'#8a6218'},status:{fontSize:11,fontWeight:'900',color:'#5a47c8',marginTop:2},name:{fontSize:18,fontWeight:'900',color:'#303342',marginTop:4},line:{fontSize:12,lineHeight:19,color:'#606674',marginTop:2},actions:{marginTop:9,gap:7},smallPrimary:{minHeight:38,borderRadius:10,backgroundColor:'#4f3ad6',alignItems:'center',justifyContent:'center'},smallPrimaryText:{fontSize:12,fontWeight:'900',color:'#fff'},remove:{minHeight:36,borderRadius:10,borderWidth:1,borderColor:'#d7d9e1',alignItems:'center',justifyContent:'center'},removeText:{fontSize:11,fontWeight:'800',color:'#777d89'},privacy:{fontSize:12,lineHeight:19,color:'#777d89',marginTop:22}});
